//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HA.PMS.OnlineSysytem
{
    using System;
    using System.Collections.Generic;
    
    public partial class FL_CustomerReturnVisit
    {
        public int ReturnId { get; set; }
        public int CustomerId { get; set; }
        public System.DateTime ReturnDate { get; set; }
        public string ReturnResult { get; set; }
        public string ReturnRecoder { get; set; }
        public Nullable<int> ReturnEmployee { get; set; }
        public string Satisfaction { get; set; }
        public Nullable<int> ReurnState { get; set; }
        public Nullable<int> StateforFile { get; set; }
        public Nullable<int> StateformEmployee { get; set; }
        public Nullable<System.DateTime> NextComeDate { get; set; }
        public string NodeforFile { get; set; }
        public string NodeforEmployee { get; set; }
        public string ReturnforFile { get; set; }
        public string ReturnforEmployee { get; set; }
        public string ReturnforDate { get; set; }
    }
}
