//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HA.PMS.OnlineSysytem
{
    using System;
    using System.Collections.Generic;
    
    public partial class FL_FinishTargetSum
    {
        public int FinishKey { get; set; }
        public int TargetID { get; set; }
        public string TargetTitle { get; set; }
        public int DepartmentID { get; set; }
        public int EmployeeID { get; set; }
        public System.DateTime UpdateTime { get; set; }
        public int CreateEmployeeID { get; set; }
        public int Year { get; set; }
        public decimal Completionrate { get; set; }
        public decimal LastYearCompletionrate { get; set; }
        public decimal OveryearRate { get; set; }
        public decimal FinishSum { get; set; }
        public decimal LastYearFinishSum { get; set; }
        public decimal OverYearFinishSum { get; set; }
        public decimal MonthPlan1 { get; set; }
        public decimal MonthFinsh1 { get; set; }
        public decimal MonthPlan2 { get; set; }
        public decimal MonthFinish2 { get; set; }
        public decimal MonthPlan3 { get; set; }
        public decimal MonthFinish3 { get; set; }
        public decimal MonthPlan4 { get; set; }
        public decimal MonthFinish4 { get; set; }
        public decimal MonthPlan5 { get; set; }
        public decimal MonthFinish5 { get; set; }
        public decimal MonthPlan6 { get; set; }
        public decimal MonthFinish6 { get; set; }
        public decimal MonthPlan7 { get; set; }
        public decimal MonthFinish7 { get; set; }
        public decimal MonthPlan8 { get; set; }
        public decimal MonthFinish8 { get; set; }
        public decimal MonthPlan9 { get; set; }
        public decimal MonthFinish9 { get; set; }
        public decimal MonthPlan10 { get; set; }
        public decimal MonthFinish10 { get; set; }
        public decimal MonthPlan11 { get; set; }
        public decimal MonthFinish11 { get; set; }
        public decimal MonthPlan12 { get; set; }
        public decimal MonthFinish12 { get; set; }
        public decimal PlanSum { get; set; }
        public string Unite { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual Sys_Employee Sys_Employee { get; set; }
        public virtual FL_Target FL_Target { get; set; }
    }
}
