//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HA.PMS.OnlineSysytem
{
    using System;
    using System.Collections.Generic;
    
    public partial class FL_OrderEarnestMoney
    {
        public int EarnestKey { get; set; }
        public int OrderID { get; set; }
        public Nullable<decimal> EarnestMoney { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<int> FinishEmpLoyee { get; set; }
        public Nullable<bool> Isfinish { get; set; }
    
        public virtual FL_Order FL_Order { get; set; }
    }
}
