//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HA.PMS.OnlineSysytem
{
    using System;
    using System.Collections.Generic;
    
    public partial class FL_Order
    {
        public FL_Order()
        {
            this.FL_OrderEarnestMoney = new HashSet<FL_OrderEarnestMoney>();
            this.FL_OrderProjectfileManager = new HashSet<FL_OrderProjectfileManager>();
        }
    
        public int OrderID { get; set; }
        public string OrderCoder { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public int FollowSum { get; set; }
        public Nullable<System.DateTime> LastFollowDate { get; set; }
        public Nullable<System.DateTime> NextFlowDate { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public Nullable<decimal> EarnestMoney { get; set; }
        public Nullable<int> Planner { get; set; }
        public Nullable<int> ComeDate { get; set; }
        public Nullable<int> ConteenID { get; set; }
        public Nullable<System.DateTime> PlanComeDate { get; set; }
        public Nullable<System.DateTime> ProjectDate { get; set; }
        public Nullable<int> FlowCount { get; set; }
        public string StateName { get; set; }
        public Nullable<decimal> TransactionProba { get; set; }
        public Nullable<bool> EarnestFinish { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> LoseDate { get; set; }
        public Nullable<bool> FileCheck { get; set; }
        public Nullable<System.DateTime> FileDate { get; set; }
    
        public virtual ICollection<FL_OrderEarnestMoney> FL_OrderEarnestMoney { get; set; }
        public virtual ICollection<FL_OrderProjectfileManager> FL_OrderProjectfileManager { get; set; }
        public virtual FL_Customers FL_Customers { get; set; }
    }
}
