//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HA.PMS.OnlineSysytem
{
    using System;
    using System.Collections.Generic;
    
    public partial class FL_Target
    {
        public FL_Target()
        {
            this.FL_FinishTargetSum = new HashSet<FL_FinishTargetSum>();
        }
    
        public int TargetID { get; set; }
        public int ChannelID { get; set; }
        public string TargetTitle { get; set; }
        public string Remark { get; set; }
        public int TargetType { get; set; }
        public string ChannelName { get; set; }
        public string Unite { get; set; }
    
        public virtual ICollection<FL_FinishTargetSum> FL_FinishTargetSum { get; set; }
    }
}
