//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HA.PMS.OnlineSysytem
{
    using System;
    using System.Collections.Generic;
    
    public partial class FL_WeddingPlanning
    {
        public int PlanningID { get; set; }
        public Nullable<int> OrderID { get; set; }
        public string OrderCoder { get; set; }
        public Nullable<int> CategoryID { get; set; }
        public Nullable<int> ParentCategoryID { get; set; }
        public Nullable<int> EmpLoyeeID { get; set; }
        public Nullable<System.DateTime> PlanFinishDate { get; set; }
        public Nullable<System.DateTime> FinishDate { get; set; }
        public string ServiceContent { get; set; }
        public string Requirement { get; set; }
        public bool IsDelete { get; set; }
        public string Remark { get; set; }
        public string Category { get; set; }
        public string CategoryItem { get; set; }
        public Nullable<int> CreateEmpLoyee { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string ImageAddress { get; set; }
        public string State { get; set; }
    }
}
