//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HA.PMS.OnlineSysytem
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PMS_WeddingEntities : DbContext
    {
        public PMS_WeddingEntities()
            : base("name=PMS_WeddingEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<FL_Cost> FL_Cost { get; set; }
        public DbSet<FL_FinishTargetSum> FL_FinishTargetSum { get; set; }
        public DbSet<View_DepartmentTarget> View_DepartmentTarget { get; set; }
        public DbSet<View_DispatchingDegreeOfSatisfaction> View_DispatchingDegreeOfSatisfaction { get; set; }
        public DbSet<View_EmployeeTarget> View_EmployeeTarget { get; set; }
        public DbSet<View_GetCost> View_GetCost { get; set; }
        public DbSet<View_GetCostItem> View_GetCostItem { get; set; }
        public DbSet<View_GetDefrreSatisaction> View_GetDefrreSatisaction { get; set; }
        public DbSet<View_GetDegreeOfSatisfaction> View_GetDegreeOfSatisfaction { get; set; }
        public DbSet<View_GetInviteCompletetoEnd> View_GetInviteCompletetoEnd { get; set; }
        public DbSet<View_GetMember> View_GetMember { get; set; }
        public DbSet<View_GetMissionSum> View_GetMissionSum { get; set; }
        public DbSet<View_GetSupplierforCarrytask> View_GetSupplierforCarrytask { get; set; }
        public DbSet<View_GetSupplierProduct> View_GetSupplierProduct { get; set; }
        public DbSet<View_GetWeddingPlanMission> View_GetWeddingPlanMission { get; set; }
        public DbSet<View_MyGoalTargetType> View_MyGoalTargetType { get; set; }
        public DbSet<Sys_Employee> Sys_Employee { get; set; }
        public DbSet<Sys_Department> Sys_Department { get; set; }
        public DbSet<Sys_UserJurisdiction> Sys_UserJurisdiction { get; set; }
        public DbSet<FL_CostforEmpLoyee> FL_CostforEmpLoyee { get; set; }
        public DbSet<FL_OrderfinalCost> FL_OrderfinalCost { get; set; }
        public DbSet<FL_MissionDetailed> FL_MissionDetailed { get; set; }
        public DbSet<FL_MissionManager> FL_MissionManager { get; set; }
        public DbSet<FL_CustomerReturnVisit> FL_CustomerReturnVisit { get; set; }
        public DbSet<FL_EmpLoyeeMissionSum> FL_EmpLoyeeMissionSum { get; set; }
        public DbSet<FL_MakeCollections> FL_MakeCollections { get; set; }
        public DbSet<FL_Message> FL_Message { get; set; }
        public DbSet<FL_MessageBoard> FL_MessageBoard { get; set; }
        public DbSet<FL_MissionChange> FL_MissionChange { get; set; }
        public DbSet<FL_MissionSumup> FL_MissionSumup { get; set; }
        public DbSet<FL_OrderEarnestMoney> FL_OrderEarnestMoney { get; set; }
        public DbSet<FL_OrderMessage> FL_OrderMessage { get; set; }
        public DbSet<FL_OrderProjectfileManager> FL_OrderProjectfileManager { get; set; }
        public DbSet<FL_Target> FL_Target { get; set; }
        public DbSet<FL_Telemarketing> FL_Telemarketing { get; set; }
        public DbSet<FL_WarningMessage> FL_WarningMessage { get; set; }
        public DbSet<FL_WeddingPlanFile> FL_WeddingPlanFile { get; set; }
        public DbSet<FL_WeddingPlanning> FL_WeddingPlanning { get; set; }
        public DbSet<Sys_Channel> Sys_Channel { get; set; }
        public DbSet<Sys_EmpLoyeeHigherups> Sys_EmpLoyeeHigherups { get; set; }
        public DbSet<Sys_EmployeeJob> Sys_EmployeeJob { get; set; }
        public DbSet<Sys_EmployeeType> Sys_EmployeeType { get; set; }
        public DbSet<Sys_JurisdictionforButton> Sys_JurisdictionforButton { get; set; }
        public DbSet<Sys_TitleNode> Sys_TitleNode { get; set; }
        public DbSet<Sys_WeddingPlanning> Sys_WeddingPlanning { get; set; }
        public DbSet<FL_OrderReference> FL_OrderReference { get; set; }
        public DbSet<FL_CostforOrder> FL_CostforOrder { get; set; }
        public DbSet<View_CustomerQuoted> View_CustomerQuoted { get; set; }
        public DbSet<View_Dispatching> View_Dispatching { get; set; }
        public DbSet<View_GetInviteCustomers> View_GetInviteCustomers { get; set; }
        public DbSet<View_GetOrderCustomers> View_GetOrderCustomers { get; set; }
        public DbSet<FL_Invite> FL_Invite { get; set; }
        public DbSet<FL_Order> FL_Order { get; set; }
        public DbSet<FL_Customers> FL_Customers { get; set; }
        public DbSet<FL_Dispatching> FL_Dispatching { get; set; }
        public DbSet<FL_ProductforDispatching> FL_ProductforDispatching { get; set; }
        public DbSet<Sys_Workgroups> Sys_Workgroups { get; set; }
        public DbSet<FL_QuotedCollectionsPlan> FL_QuotedCollectionsPlan { get; set; }
        public DbSet<FL_QuotedPrice> FL_QuotedPrice { get; set; }
        public DbSet<SS_Report> SS_Report { get; set; }
    }
}
