//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HA.PMS.OnlineSysytem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sys_JurisdictionforButton
    {
        public int ButtonKey { get; set; }
        public Nullable<int> JurisdictionID { get; set; }
        public Nullable<int> ControlID { get; set; }
        public Nullable<int> ChannelID { get; set; }
        public Nullable<bool> IsClose { get; set; }
    }
}
