//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HA.PMS.OnlineSysytem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sys_EmpLoyeeHigherups
    {
        public int UpKey { get; set; }
        public int EmployeeID { get; set; }
        public int Type { get; set; }
        public string FunctionCode { get; set; }
        public Nullable<System.DateTime> createTime { get; set; }
        public Nullable<bool> IsDelete { get; set; }
    
        public virtual Sys_Employee Sys_Employee { get; set; }
    }
}
