//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HA.PMS.OnlineSysytem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sys_Department
    {
        public Sys_Department()
        {
            this.Sys_Employee = new HashSet<Sys_Employee>();
        }
    
        public int DepartmentID { get; set; }
        public string DepartmentName { get; set; }
        public Nullable<int> Parent { get; set; }
        public string SortOrder { get; set; }
        public Nullable<System.DateTime> createTime { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public Nullable<int> DepartmentManager { get; set; }
        public string Brand { get; set; }
        public Nullable<int> ItemLevel { get; set; }
        public Nullable<int> DataSource { get; set; }
    
        public virtual ICollection<Sys_Employee> Sys_Employee { get; set; }
    }
}
