//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HA.PMS.OnlineSysytem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sys_Channel
    {
        public int ChannelID { get; set; }
        public string ChannelName { get; set; }
        public string ChannelAddress { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<int> Parent { get; set; }
        public Nullable<bool> IsMenu { get; set; }
        public string ChannelGetType { get; set; }
        public string StyleSheethem { get; set; }
        public Nullable<int> OrderCode { get; set; }
        public Nullable<bool> IsPublic { get; set; }
    }
}
