//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HA.PMS.OnlineSysytem
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_GetCostItem
    {
        public int CostID { get; set; }
        public int KindID { get; set; }
        public string ServiceContent { get; set; }
        public decimal PlannedExpenditure { get; set; }
        public decimal ActualExpenditure { get; set; }
        public string Expenseaccount { get; set; }
        public bool IsDelete { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string InsideRemark { get; set; }
        public int CostKey { get; set; }
        public string ActualWorkload { get; set; }
        public string CellPhone { get; set; }
        public Nullable<int> KindType { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public Nullable<int> SupplierID { get; set; }
        public Nullable<decimal> ProfitMargin { get; set; }
        public Nullable<int> OrderID { get; set; }
        public Nullable<decimal> Cost { get; set; }
        public Nullable<int> CreateEmpLoyee { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
    }
}
