//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HA.PMS.OnlineSysytem
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_DepartmentTarget
    {
        public string TargetTitle { get; set; }
        public Nullable<decimal> MonthPlan1 { get; set; }
        public Nullable<decimal> MonthFinsh1 { get; set; }
        public Nullable<decimal> MonthPlan2 { get; set; }
        public Nullable<decimal> MonthFinish2 { get; set; }
        public Nullable<decimal> MonthPlan3 { get; set; }
        public Nullable<decimal> MonthFinish3 { get; set; }
        public Nullable<decimal> MonthPlan4 { get; set; }
        public Nullable<decimal> MonthFinish4 { get; set; }
        public Nullable<decimal> MonthPlan5 { get; set; }
        public Nullable<decimal> MonthFinish5 { get; set; }
        public Nullable<decimal> MonthPlan6 { get; set; }
        public Nullable<decimal> MonthFinish6 { get; set; }
        public Nullable<decimal> MonthPlan7 { get; set; }
        public Nullable<decimal> MonthFinish7 { get; set; }
        public Nullable<decimal> MonthPlan8 { get; set; }
        public Nullable<decimal> MonthFinish8 { get; set; }
        public Nullable<decimal> MonthPlan9 { get; set; }
        public Nullable<decimal> MonthFinish9 { get; set; }
        public Nullable<decimal> MonthPlan10 { get; set; }
        public Nullable<decimal> MonthFinish10 { get; set; }
        public Nullable<decimal> MonthPlan11 { get; set; }
        public Nullable<decimal> MonthFinish11 { get; set; }
        public Nullable<decimal> MonthPlan12 { get; set; }
        public Nullable<decimal> MonthFinish12 { get; set; }
    }
}
