//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HA.PMS.SnManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table_SnManager
    {
        public int SnID { get; set; }
        public string Sn { get; set; }
        public string CpuID { get; set; }
        public string DiskID { get; set; }
        public System.DateTime CreateDate { get; set; }
        public System.DateTime CreateTime { get; set; }
        public Nullable<int> CreateEmpLoyee { get; set; }
        public string EmpLoyeeUpdate { get; set; }
        public string SHA1 { get; set; }
        public string MD5 { get; set; }
        public Nullable<bool> IsClose { get; set; }
        public bool FirstCreate { get; set; }
        public string Customer { get; set; }
        public Nullable<System.DateTime> OverDate { get; set; }
    }
}
