//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HA.PMS.DataAssmblly
{
    using System;
    using System.Collections.Generic;
    
    public partial class CA_CompanyFile
    {
        public int FileID { get; set; }
        public string FileURL { get; set; }
        public string FileName { get; set; }
        public Nullable<int> ItemLevel { get; set; }
        public Nullable<int> ParentFileId { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<int> CreateEmployee { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public string Remark { get; set; }
        public string PureRoute { get; set; }
    }
}
