//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HA.PMS.DataAssmblly
{
    using System;
    using System.Collections.Generic;
    
    public partial class CA_SaleTarget
    {
        public int TargetKey { get; set; }
        public Nullable<decimal> Target { get; set; }
        public Nullable<int> Type { get; set; }
        public Nullable<decimal> Year { get; set; }
        public Nullable<decimal> Quarter { get; set; }
        public Nullable<decimal> Month { get; set; }
        public Nullable<int> EmpLoyeeID { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
    }
}
