//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HA.PMS.DataAssmblly
{
    using System;
    using System.Collections.Generic;
    
    public partial class CC_PackageReserve
    {
        public int SourceKey { get; set; }
        public string DateItem { get; set; }
        public System.DateTime PartyDate { get; set; }
        public int EmployeeID { get; set; }
        public int State { get; set; }
        public string Node { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<int> UpdateEmployee { get; set; }
        public bool IsDelete { get; set; }
        public int PackageID { get; set; }
    }
}
