//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HA.PMS.DataAssmblly
{
    using System;
    using System.Collections.Generic;
    
    public partial class CS_ComplainCustomersOrderEmployee
    {
        public int ComplainID { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public string ComplainContent { get; set; }
        public Nullable<System.DateTime> ComplainDate { get; set; }
        public string ComplainRemark { get; set; }
        public string ReturnContent { get; set; }
        public Nullable<System.DateTime> ReturnDate { get; set; }
        public Nullable<int> ComplainEmployeeId { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public string Groom { get; set; }
        public string BrideCellPhone { get; set; }
        public Nullable<System.DateTime> PartyDate { get; set; }
        public string Wineshop { get; set; }
        public Nullable<int> Planner { get; set; }
        public Nullable<decimal> EarnestMoney { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public string EmployeeName { get; set; }
        public int OrderID { get; set; }
        public Nullable<System.DateTime> LastFollowDate { get; set; }
        public string OrderCoder { get; set; }
        public string CustomerStatus { get; set; }
    }
}
