//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HA.PMS.DataAssmblly
{
    using System;
    using System.Collections.Generic;
    
    public partial class CS_DegreeOfSatisfaction
    {
        public CS_DegreeOfSatisfaction()
        {
            this.CS_DegreeOfSatisfactionContent = new HashSet<CS_DegreeOfSatisfactionContent>();
        }
    
        public int DofKey { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public string SumDof { get; set; }
        public string DofContent { get; set; }
        public Nullable<System.DateTime> DofDate { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public string DegreeResult { get; set; }
        public Nullable<int> State { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
        public Nullable<int> UpdateEmployeeID { get; set; }
        public Nullable<System.DateTime> PlanDate { get; set; }
    
        public virtual ICollection<CS_DegreeOfSatisfactionContent> CS_DegreeOfSatisfactionContent { get; set; }
        public virtual FL_Customers FL_Customers { get; set; }
    }
}
