//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HA.PMS.DataAssmblly
{
    using System;
    using System.Collections.Generic;
    
    public partial class CS_DegreeOfSatisfactionContent
    {
        public int TypeKey { get; set; }
        public int DofKey { get; set; }
        public int ItemKey { get; set; }
        public int AssessId { get; set; }
        public string StationContent { get; set; }
    
        public virtual CS_DegreeAssessResult CS_DegreeAssessResult { get; set; }
        public virtual CS_DegreeOfSatisfaction CS_DegreeOfSatisfaction { get; set; }
        public virtual CS_DegreeOfSatisfactionItem CS_DegreeOfSatisfactionItem { get; set; }
    }
}
