//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HA.PMS.DataAssmblly
{
    using System;
    using System.Collections.Generic;
    
    public partial class FD_BanquetHall
    {
        public int BanquetHallID { get; set; }
        public Nullable<int> HotelId { get; set; }
        public string HallName { get; set; }
        public string FloorName { get; set; }
        public Nullable<decimal> FloorHeight { get; set; }
        public Nullable<int> DeskCount { get; set; }
        public string BanquetExplain { get; set; }
        public string Color1 { get; set; }
        public string Color2 { get; set; }
        public string Color3 { get; set; }
        public Nullable<decimal> Area { get; set; }
        public Nullable<decimal> Meal { get; set; }
        public Nullable<decimal> EmptyHigh { get; set; }
    }
}
