//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HA.PMS.DataAssmblly
{
    using System;
    using System.Collections.Generic;
    
    public partial class FD_CelebrationPackageMakeQuotedPrice
    {
        public int MakeId { get; set; }
        public int CategoryProjectId { get; set; }
        public Nullable<int> CategorySecondId { get; set; }
        public string ProductService { get; set; }
        public string SpecificRequirements { get; set; }
        public string ImageUrl { get; set; }
        public Nullable<decimal> ProductPrice { get; set; }
        public Nullable<int> Count { get; set; }
        public Nullable<decimal> SmallSum { get; set; }
        public string Explain { get; set; }
        public bool IsDelete { get; set; }
        public Nullable<int> PackageID { get; set; }
        public Nullable<int> ProductId { get; set; }
    
        public virtual FD_Category FD_Category { get; set; }
        public virtual FD_CelebrationPackage FD_CelebrationPackage { get; set; }
    }
}
