//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HA.PMS.DataAssmblly
{
    using System;
    using System.Collections.Generic;
    
    public partial class FD_CelebrationPackageImage
    {
        public int ImageId { get; set; }
        public string ImageUrl { get; set; }
        public int PackageId { get; set; }
        public bool IsDelete { get; set; }
        public Nullable<int> SortNumber { get; set; }
        public string ImageName { get; set; }
        public string Message { get; set; }
    }
}
