//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HA.PMS.DataAssmblly
{
    using System;
    using System.Collections.Generic;
    
    public partial class FD_CelebrationPackage
    {
        public FD_CelebrationPackage()
        {
            this.FD_CelebrationPackageMakeQuotedPrice = new HashSet<FD_CelebrationPackageMakeQuotedPrice>();
        }
    
        public int PackageID { get; set; }
        public string PackageTitle { get; set; }
        public int PackageSkip { get; set; }
        public string PackageHot { get; set; }
        public Nullable<decimal> PackagePrice { get; set; }
        public Nullable<decimal> PackagePreferentiaPrice { get; set; }
        public string PackageDirections { get; set; }
        public int ProductId { get; set; }
        public string PackageDetails { get; set; }
        public bool IsDelete { get; set; }
        public string PackageImgTop { get; set; }
        public Nullable<int> SpanID { get; set; }
        public Nullable<int> QuotedPriceID { get; set; }
        public Nullable<System.DateTime> PackageDate { get; set; }
        public Nullable<int> PackageType { get; set; }
        public Nullable<int> CreateEmployee { get; set; }
        public Nullable<int> DepartmentID { get; set; }
        public Nullable<bool> IsMake { get; set; }
        public string DesignNotes { get; set; }
        public Nullable<int> PackageSum { get; set; }
        public Nullable<int> DesignEmployee { get; set; }
    
        public virtual FD_CelebrationPackageStyle FD_CelebrationPackageStyle { get; set; }
        public virtual ICollection<FD_CelebrationPackageMakeQuotedPrice> FD_CelebrationPackageMakeQuotedPrice { get; set; }
    }
}
