//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HA.PMS.DataAssmblly
{
    using System;
    using System.Collections.Generic;
    
    public partial class FD_CelebrationPackageStyle
    {
        public FD_CelebrationPackageStyle()
        {
            this.FD_CelebrationPackage = new HashSet<FD_CelebrationPackage>();
        }
    
        public int StyleId { get; set; }
        public string StyleName { get; set; }
        public string StyleExplain { get; set; }
        public Nullable<bool> IsDelete { get; set; }
    
        public virtual ICollection<FD_CelebrationPackage> FD_CelebrationPackage { get; set; }
    }
}
