//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HA.PMS.DataAssmblly
{
    using System;
    using System.Collections.Generic;
    
    public partial class FD_ChannelType
    {
        public FD_ChannelType()
        {
            this.FD_SaleSources = new HashSet<FD_SaleSources>();
        }
    
        public int ChannelTypeId { get; set; }
        public string ChannelTypeName { get; set; }
        public bool IsDelete { get; set; }
    
        public virtual ICollection<FD_SaleSources> FD_SaleSources { get; set; }
    }
}
