//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HA.PMS.DataAssmblly
{
    using System;
    using System.Collections.Generic;
    
    public partial class FD_GuardianType
    {
        public FD_GuardianType()
        {
            this.FD_FourGuardian = new HashSet<FD_FourGuardian>();
        }
    
        public int TypeId { get; set; }
        public string TypeName { get; set; }
        public bool IsDelete { get; set; }
    
        public virtual ICollection<FD_FourGuardian> FD_FourGuardian { get; set; }
    }
}
