//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HA.PMS.DataAssmblly
{
    using System;
    using System.Collections.Generic;
    
    public partial class FD_GuardianImage
    {
        public int GuardianImageID { get; set; }
        public int FourGuardianId { get; set; }
        public string ImagePath { get; set; }
        public Nullable<System.DateTime> Createtime { get; set; }
        public Nullable<int> CreateEmployee { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public string ImageName { get; set; }
    }
}
