//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HA.PMS.DataAssmblly
{
    using System;
    using System.Collections.Generic;
    
    public partial class FD_ImageType
    {
        public FD_ImageType()
        {
            this.FD_ImageWarehouse = new HashSet<FD_ImageWarehouse>();
            this.FD_PPTWarehouse = new HashSet<FD_PPTWarehouse>();
        }
    
        public int TypeId { get; set; }
        public string TypeName { get; set; }
        public bool IsDelete { get; set; }
    
        public virtual ICollection<FD_ImageWarehouse> FD_ImageWarehouse { get; set; }
        public virtual ICollection<FD_PPTWarehouse> FD_PPTWarehouse { get; set; }
    }
}
