//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HA.PMS.DataAssmblly
{
    using System;
    using System.Collections.Generic;
    
    public partial class FD_PayNeedRabate
    {
        public int Id { get; set; }
        public Nullable<int> SourceID { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public Nullable<System.DateTime> PartyDay { get; set; }
        public Nullable<int> State { get; set; }
        public Nullable<System.DateTime> PayDate { get; set; }
        public Nullable<decimal> PayMoney { get; set; }
        public string MoneyPerson { get; set; }
        public Nullable<decimal> OrderMoney { get; set; }
        public string MoneyCell { get; set; }
        public string Paypolicy { get; set; }
        public string OperEmployee { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public Nullable<int> ChannelTypeId { get; set; }
        public Nullable<bool> IsFinish { get; set; }
        public string Referee { get; set; }
        public string CostPhone { get; set; }
        public Nullable<int> EmpLoyeeID { get; set; }
    }
}
