//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HA.PMS.DataAssmblly
{
    using System;
    using System.Collections.Generic;
    
    public partial class FD_PPTWarehouse
    {
        public int PPTID { get; set; }
        public string PPTTitle { get; set; }
        public int ImageTypeId { get; set; }
        public string PPTUrl { get; set; }
        public System.DateTime LoadTime { get; set; }
        public int LoadPerson { get; set; }
        public bool IsDelete { get; set; }
        public string LoadLabel { get; set; }
    
        public virtual FD_ImageType FD_ImageType { get; set; }
        public virtual Sys_Employee Sys_Employee { get; set; }
    }
}
