//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HA.PMS.DataAssmblly
{
    using System;
    using System.Collections.Generic;
    
    public partial class FD_QuotedCatgory
    {
        public FD_QuotedCatgory()
        {
            this.FD_QuotedProduct = new HashSet<FD_QuotedProduct>();
        }
    
        public int QCKey { get; set; }
        public string Title { get; set; }
        public Nullable<int> Parent { get; set; }
        public string SortOrder { get; set; }
        public Nullable<int> ItemLevel { get; set; }
        public Nullable<int> Productproperty { get; set; }
        public string MediaFileList { get; set; }
        public Nullable<int> Type { get; set; }
        public Nullable<bool> IsDelete { get; set; }
    
        public virtual ICollection<FD_QuotedProduct> FD_QuotedProduct { get; set; }
    }
}
