//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HA.PMS.DataAssmblly
{
    using System;
    using System.Collections.Generic;
    
    public partial class FD_QuotedProduct
    {
        public int ProductKey { get; set; }
        public string Keys { get; set; }
        public int QCKey { get; set; }
        public string ProductCount { get; set; }
    
        public virtual FD_QuotedCatgory FD_QuotedCatgory { get; set; }
    }
}
