//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HA.PMS.DataAssmblly
{
    using System;
    using System.Collections.Generic;
    
    public partial class FD_Supplier
    {
        public FD_Supplier()
        {
            this.FD_Product = new HashSet<FD_Product>();
        }
    
        public int SupplierID { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public Nullable<System.DateTime> StarDate { get; set; }
        public string Linkman { get; set; }
        public string TelPhone { get; set; }
        public string QQ { get; set; }
        public string Email { get; set; }
        public string CellPhone { get; set; }
        public string AccountInformation { get; set; }
        public Nullable<int> CategoryID { get; set; }
        public bool IsDelete { get; set; }
        public Nullable<int> CreateEmployeeId { get; set; }
        public Nullable<int> SupplyCount { get; set; }
        public Nullable<int> ErrorCount { get; set; }
        public string BankName { get; set; }
    
        public virtual ICollection<FD_Product> FD_Product { get; set; }
    }
}
