//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HA.PMS.DataAssmblly
{
    using System;
    using System.Collections.Generic;
    
    public partial class FD_SupplierErrorLog
    {
        public int ErrorLogId { get; set; }
        public int OrderId { get; set; }
        public string EvaluationObject { get; set; }
        public Nullable<bool> HaveError { get; set; }
        public string EvaluationExplain { get; set; }
        public string ImprovementSuggestions { get; set; }
        public string EvaluationPerson { get; set; }
        public Nullable<System.DateTime> EvaluationDate { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public string EvaluationResult { get; set; }
    }
}
