//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HA.PMS.DataAssmblly
{
    using System;
    using System.Collections.Generic;
    
    public partial class FD_StorehouseSourceProduct
    {
        public int SourceProductId { get; set; }
        public string SourceProductName { get; set; }
        public System.DateTime PutStoreDate { get; set; }
        public Nullable<int> ProductCategory { get; set; }
        public Nullable<int> ProductProject { get; set; }
        public string Specifications { get; set; }
        public string Data { get; set; }
        public Nullable<decimal> PurchasePrice { get; set; }
        public Nullable<decimal> SaleOrice { get; set; }
        public string Unit { get; set; }
        public Nullable<int> SourceCount { get; set; }
        public Nullable<int> OperCount { get; set; }
        public string ProductState { get; set; }
        public Nullable<int> StorehouseSourceID { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public string Remark { get; set; }
        public Nullable<bool> IsDisposible { get; set; }
        public Nullable<int> StorehouseID { get; set; }
        public string Position { get; set; }
    }
}
