//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HA.PMS.DataAssmblly
{
    using System;
    using System.Collections.Generic;
    
    public partial class FD_SaleSources
    {
        public int SourceID { get; set; }
        public string Sourcename { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public System.DateTime ProlongationDate { get; set; }
        public Nullable<int> ProlongationEmployee { get; set; }
        public Nullable<int> MaintenanceEmployee { get; set; }
        public string Type { get; set; }
        public Nullable<bool> NeedRebate { get; set; }
        public string Address { get; set; }
        public Nullable<int> ChannelTypeId { get; set; }
        public string Fax { get; set; }
        public string Tactcontacts1 { get; set; }
        public string Tactcontacts2 { get; set; }
        public string Tactcontacts3 { get; set; }
        public string TactcontactsType1 { get; set; }
        public string TactcontactsType2 { get; set; }
        public string TactcontactsType3 { get; set; }
        public string TactcontactsJob1 { get; set; }
        public string TactcontactsJob2 { get; set; }
        public string TactcontactsJob3 { get; set; }
        public string TactcontactsPhone1 { get; set; }
        public string TactcontactsPhone2 { get; set; }
        public string TactcontactsPhone3 { get; set; }
        public string Email1 { get; set; }
        public string Email2 { get; set; }
        public string Email3 { get; set; }
        public string QQ1 { get; set; }
        public string QQ2 { get; set; }
        public string QQ3 { get; set; }
        public string Weibo1 { get; set; }
        public string Weibo2 { get; set; }
        public string Weibo3 { get; set; }
        public string WenXin1 { get; set; }
        public string WenXin2 { get; set; }
        public string WenXin3 { get; set; }
        public string Synopsis { get; set; }
        public string Preferentialpolicy { get; set; }
        public string Rebatepolicy { get; set; }
        public string Node1 { get; set; }
        public string Node2 { get; set; }
        public string Node3 { get; set; }
        public string BankName { get; set; }
        public string BankCard { get; set; }
        public string Letter { get; set; }
    
        public virtual FD_ChannelType FD_ChannelType { get; set; }
    }
}
