//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HA.PMS.DataAssmblly
{
    using System;
    using System.Collections.Generic;
    
    public partial class FL_CostforOrder
    {
        public int CostID { get; set; }
        public int OrderID { get; set; }
        public int CustomerID { get; set; }
        public int DispatchingID { get; set; }
        public System.DateTime CreateDate { get; set; }
        public int CreateEmpLoyee { get; set; }
        public string Node { get; set; }
        public string Name { get; set; }
        public decimal PlanCost { get; set; }
        public decimal FinishCost { get; set; }
        public int RowType { get; set; }
        public bool Lock { get; set; }
        public System.DateTime LockDate { get; set; }
        public int LockEmployee { get; set; }
    }
}
