//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HA.PMS.DataAssmblly
{
    using System;
    using System.Collections.Generic;
    
    public partial class FL_CustomersOrderReturn
    {
        public int OrderID { get; set; }
        public string OrderCoder { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public int FollowSum { get; set; }
        public Nullable<System.DateTime> LastFollowDate { get; set; }
        public Nullable<System.DateTime> NextFlowDate { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public Nullable<decimal> EarnestMoney { get; set; }
        public Nullable<int> Planner { get; set; }
        public Nullable<int> ComeDate { get; set; }
        public Nullable<int> ConteenID { get; set; }
        public Nullable<System.DateTime> PlanComeDate { get; set; }
        public Nullable<System.DateTime> ProjectDate { get; set; }
        public Nullable<int> FlowCount { get; set; }
        public string StateName { get; set; }
        public int ReturnId { get; set; }
        public System.DateTime ReturnDate { get; set; }
        public string ReturnResult { get; set; }
        public string ReturnRecoder { get; set; }
        public Nullable<int> ReturnEmployee { get; set; }
        public string Satisfaction { get; set; }
        public string Groom { get; set; }
        public string GroomCellPhone { get; set; }
        public Nullable<int> State { get; set; }
        public Nullable<bool> IsLose { get; set; }
        public Nullable<System.DateTime> PartyDate { get; set; }
        public string Address { get; set; }
        public Nullable<System.DateTime> Todate { get; set; }
        public string Wineshop { get; set; }
        public string CustomerStatus { get; set; }
        public string StoreAddress { get; set; }
    }
}
