//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HA.PMS.DataAssmblly
{
    using System;
    using System.Collections.Generic;
    
    public partial class FL_CustomersSaleSources
    {
        public int ChannelType { get; set; }
        public System.DateTime ProlongationDate { get; set; }
        public Nullable<int> ProlongationEmployee { get; set; }
        public string EmployeeName { get; set; }
        public string Channel { get; set; }
        public string Referee { get; set; }
        public Nullable<System.DateTime> PartyDate { get; set; }
        public string Groom { get; set; }
        public string CustomerStatus { get; set; }
        public int CustomerID { get; set; }
        public string Tactcontacts1 { get; set; }
        public string Tactcontacts2 { get; set; }
        public string Tactcontacts3 { get; set; }
    }
}
