//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HA.PMS.DataAssmblly
{
    using System;
    using System.Collections.Generic;
    
    public partial class FL_Designclass
    {
        public int DesignclassID { get; set; }
        public string Title { get; set; }
        public string Node { get; set; }
        public string Supplier { get; set; }
        public int PurchaseQuantity { get; set; }
        public decimal PurchasePrice { get; set; }
        public int RealQuantity { get; set; }
        public string Unit { get; set; }
        public System.DateTime CreateDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public int CreateEmployee { get; set; }
        public Nullable<int> UodateEmployee { get; set; }
        public int CustomerID { get; set; }
        public decimal TotalPrice { get; set; }
        public int QuotedID { get; set; }
        public int DispatchingID { get; set; }
        public string Material { get; set; }
        public Nullable<int> State { get; set; }
        public string Spec { get; set; }
        public Nullable<int> Evaluation { get; set; }
        public string Advance { get; set; }
        public string ShortCome { get; set; }
        public Nullable<decimal> ActualSumTotal { get; set; }
    }
}
