//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HA.PMS.DataAssmblly
{
    using System;
    using System.Collections.Generic;
    
    public partial class FL_DetailsQuotedPrice
    {
        public int DetailsID { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public Nullable<int> QuotedID { get; set; }
        public Nullable<System.DateTime> QuotedCreateDate { get; set; }
        public string QuotedContent { get; set; }
        public Nullable<System.DateTime> NextFollowDate { get; set; }
        public Nullable<int> CreateEmployee { get; set; }
    }
}
