//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HA.PMS.DataAssmblly
{
    using System;
    using System.Collections.Generic;
    
    public partial class FL_DispatchAllProducts
    {
        public int Keys { get; set; }
        public Nullable<int> KindID { get; set; }
        public Nullable<int> Expr1 { get; set; }
        public string ProductName { get; set; }
        public Nullable<int> ProductCategory { get; set; }
        public Nullable<int> ProjectCategory { get; set; }
        public string Expr2 { get; set; }
        public string Data { get; set; }
        public Nullable<decimal> Expr3 { get; set; }
        public Nullable<decimal> SalePrice { get; set; }
        public string Expr4 { get; set; }
        public Nullable<bool> Expr5 { get; set; }
        public string Explain { get; set; }
        public Nullable<int> Count { get; set; }
        public string SupplierName { get; set; }
        public string OrderCoder { get; set; }
        public int ProeuctKey { get; set; }
        public string Unit { get; set; }
        public string Specifications { get; set; }
        public string ServiceContent { get; set; }
        public string Requirement { get; set; }
        public string ImageUrl { get; set; }
        public Nullable<decimal> UnitPrice { get; set; }
        public Nullable<decimal> PurchasePrice { get; set; }
        public int Quantity { get; set; }
        public Nullable<decimal> Subtotal { get; set; }
        public string Remark { get; set; }
        public bool IsDelete { get; set; }
        public string CategoryName { get; set; }
        public Nullable<int> CategoryID { get; set; }
        public Nullable<int> ParentCategoryID { get; set; }
        public Nullable<int> ProductID { get; set; }
        public int DispatchingID { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public Nullable<int> Type { get; set; }
        public Nullable<System.DateTime> PlannedCompletionTime { get; set; }
        public Nullable<System.DateTime> FinishDate { get; set; }
        public Nullable<bool> IsSvae { get; set; }
        public Nullable<int> ChangeID { get; set; }
        public Nullable<int> ParentID { get; set; }
        public Nullable<int> Batch { get; set; }
        public Nullable<int> RowType { get; set; }
        public Nullable<int> ItemLevel { get; set; }
        public Nullable<int> ParentDispatchingID { get; set; }
        public string ParentCategoryName { get; set; }
        public Nullable<int> OrderID { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public Nullable<bool> NewAdd { get; set; }
        public Nullable<decimal> ItemAmount { get; set; }
        public Nullable<decimal> ItemSaleAmount { get; set; }
        public Nullable<int> Productproperty { get; set; }
        public Nullable<System.DateTime> Updatetime { get; set; }
        public Nullable<bool> IsGet { get; set; }
        public Nullable<int> Expr6 { get; set; }
    }
}
