//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HA.PMS.DataAssmblly
{
    using System;
    using System.Collections.Generic;
    
    public partial class FL_DispathingSatisfaction
    {
        public int SatisfactionId { get; set; }
        public Nullable<int> DispatchingID { get; set; }
        public string SatisfactionName { get; set; }
        public string SatisfactionContent { get; set; }
        public Nullable<int> SaEvaluationId { get; set; }
        public string SatisfactionRemark { get; set; }
        public string EvaluationName { get; set; }
        public string EvaluationContent { get; set; }
        public Nullable<int> EvaluationId { get; set; }
        public string EvaluationRemark { get; set; }
        public Nullable<int> CreateEmployee { get; set; }
    }
}
