//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HA.PMS.DataAssmblly
{
    using System;
    using System.Collections.Generic;
    
    public partial class FL_DispatchingTeamEmployee
    {
        public int TeamEmployee { get; set; }
        public int DispatchingID { get; set; }
        public string TelPhone { get; set; }
        public string EmployeeType { get; set; }
        public string EmployeeName { get; set; }
        public string Specificrequirements { get; set; }
        public decimal Amount { get; set; }
        public System.DateTime CreateDate { get; set; }
        public int EmployeeID { get; set; }
        public int StateID { get; set; }
        public string Sex { get; set; }
        public Nullable<int> Typer { get; set; }
    }
}
