//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HA.PMS.DataAssmblly
{
    using System;
    using System.Collections.Generic;
    
    public partial class FL_DispatchingImage
    {
        public int ImageID { get; set; }
        public int DispatchingID { get; set; }
        public string Filename { get; set; }
        public string FileAddress { get; set; }
        public System.DateTime CreateDate { get; set; }
        public int SortOrder { get; set; }
        public int KindID { get; set; }
        public int Type { get; set; }
        public Nullable<int> StateKey { get; set; }
    }
}
