//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HA.PMS.DataAssmblly
{
    using System;
    using System.Collections.Generic;
    
    public partial class FL_DispatchingState
    {
        public int StateKey { get; set; }
        public int DispatchingID { get; set; }
        public int State { get; set; }
        public System.DateTime CreateDate { get; set; }
        public int CreateEmpLoyee { get; set; }
        public bool IsUse { get; set; }
        public int StateEmpLoyee { get; set; }
        public Nullable<int> StateItemLevel { get; set; }
        public Nullable<int> StateCatgoryID { get; set; }
        public Nullable<int> StateParentCatgory { get; set; }
        public Nullable<System.DateTime> PlanDate { get; set; }
        public Nullable<System.DateTime> FinishDate { get; set; }
        public string FinishAmount { get; set; }
    }
}
