//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HA.PMS.DataAssmblly
{
    using System;
    using System.Collections.Generic;
    
    public partial class FL_EmpLoyeeMissionSum
    {
        public int FSKey { get; set; }
        public int EmpLoyeeID { get; set; }
        public string EmployeeName { get; set; }
        public int DepartmentID { get; set; }
        public string DepartmentName { get; set; }
        public int FlowSum { get; set; }
        public int FinishSUm { get; set; }
        public decimal FinishRatio { get; set; }
        public int DoingSum { get; set; }
        public int WaitDoingSum { get; set; }
        public int NewSum { get; set; }
        public System.DateTime Updatetime { get; set; }
        public System.DateTime CreateDate { get; set; }
    }
}
