//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HA.PMS.DataAssmblly
{
    using System;
    using System.Collections.Generic;
    
    public partial class FL_Evaulation
    {
        public int EvalID { get; set; }
        public Nullable<int> EvalWorkID { get; set; }
        public string EvalTitle { get; set; }
        public string EvalImageName { get; set; }
        public string EvalImagePath { get; set; }
        public string EvalDescription { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<int> CreateEmployee { get; set; }
        public Nullable<int> Type { get; set; }
        public Nullable<int> IsShow { get; set; }
        public Nullable<int> CaseID { get; set; }
    }
}
