//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HA.PMS.DataAssmblly
{
    using System;
    using System.Collections.Generic;
    
    public partial class FL_FlowerCost
    {
        public int Flowerkey { get; set; }
        public string FLowername { get; set; }
        public decimal SalePrice { get; set; }
        public decimal CostPrice { get; set; }
        public decimal Quantity { get; set; }
        public int CustomerID { get; set; }
        public Nullable<int> DispatchingID { get; set; }
        public Nullable<int> QuotedID { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public int CreateEmployeeID { get; set; }
        public Nullable<decimal> CostSumPrice { get; set; }
        public Nullable<decimal> SaleSumPrice { get; set; }
        public Nullable<int> BuyType { get; set; }
        public string Unite { get; set; }
        public string Node { get; set; }
        public Nullable<int> CostSumId { get; set; }
        public string UploadImage { get; set; }
        public string ImageName { get; set; }
    }
}
