//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HA.PMS.DataAssmblly
{
    using System;
    using System.Collections.Generic;
    
    public partial class FL_InvtieContent
    {
        public int ContentID { get; set; }
        public Nullable<int> InviteID { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public Nullable<System.DateTime> CommunicationTime { get; set; }
        public string CommunicationContent { get; set; }
        public string LoseContent { get; set; }
        public string State { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<int> EmpLoyeeID { get; set; }
        public Nullable<int> SortOrder { get; set; }
        public Nullable<System.DateTime> NextPlanDate { get; set; }
    
        public virtual FL_Invite FL_Invite { get; set; }
    }
}
