//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HA.PMS.DataAssmblly
{
    using System;
    using System.Collections.Generic;
    
    public partial class FL_Invite
    {
        public FL_Invite()
        {
            this.FL_InvtieContent = new HashSet<FL_InvtieContent>();
        }
    
        public int InviteID { get; set; }
        public int CustomerID { get; set; }
        public Nullable<int> EmpLoyeeID { get; set; }
        public Nullable<System.DateTime> ComeDate { get; set; }
        public Nullable<int> ToDepartMent { get; set; }
        public Nullable<int> ToEmpLoyee { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<int> CreateEmployee { get; set; }
        public string CreateEmployeeName { get; set; }
        public Nullable<int> FllowCount { get; set; }
        public Nullable<System.DateTime> AgainDate { get; set; }
        public Nullable<System.DateTime> LastFollowDate { get; set; }
        public Nullable<int> ContentID { get; set; }
        public string Title { get; set; }
        public Nullable<int> OrderEmpLoyeeID { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<System.DateTime> ChangeDate { get; set; }
    
        public virtual ICollection<FL_InvtieContent> FL_InvtieContent { get; set; }
        public virtual FL_Customers FL_Customers { get; set; }
    }
}
