//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HA.PMS.DataAssmblly
{
    using System;
    using System.Collections.Generic;
    
    public partial class FL_MissionManager
    {
        public FL_MissionManager()
        {
            this.FL_MissionDetailed = new HashSet<FL_MissionDetailed>();
            this.FL_MissionSumup = new HashSet<FL_MissionSumup>();
        }
    
        public int MissionID { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public Nullable<int> DepartmentID { get; set; }
        public string MissionTitle { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public Nullable<int> Type { get; set; }
        public Nullable<int> MissionType { get; set; }
        public string CheckContent { get; set; }
        public Nullable<bool> IsCheck { get; set; }
        public Nullable<int> CheckEmpLoyeeID { get; set; }
        public Nullable<int> CheckState { get; set; }
        public Nullable<System.DateTime> TimerStar { get; set; }
        public Nullable<System.DateTime> TimerEnd { get; set; }
        public Nullable<bool> IsOver { get; set; }
        public Nullable<bool> IsAppraise { get; set; }
    
        public virtual ICollection<FL_MissionDetailed> FL_MissionDetailed { get; set; }
        public virtual ICollection<FL_MissionSumup> FL_MissionSumup { get; set; }
    }
}
