//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HA.PMS.DataAssmblly
{
    using System;
    using System.Collections.Generic;
    
    public partial class FL_MissionDetailedEmployee
    {
        public int DetailedID { get; set; }
        public Nullable<int> MissionID { get; set; }
        public string MissionName { get; set; }
        public string WorkNode { get; set; }
        public string FinishStandard { get; set; }
        public Nullable<int> ChecksEmployee { get; set; }
        public Nullable<System.DateTime> FinishDate { get; set; }
        public Nullable<int> Countdown { get; set; }
        public string Emergency { get; set; }
        public Nullable<int> EmpLoyeeID { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public string Attachment { get; set; }
        public string FinishNode { get; set; }
        public string FinishFile { get; set; }
        public Nullable<System.DateTime> StarDate { get; set; }
        public Nullable<int> ChecksState { get; set; }
        public Nullable<System.DateTime> ChecksDate { get; set; }
        public string ChecksNode { get; set; }
        public string KeyWords { get; set; }
        public Nullable<int> ChannelID { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> PlanDate { get; set; }
        public string ChangeNode { get; set; }
        public string ChecksChangeNode { get; set; }
        public Nullable<int> Type { get; set; }
        public string TypeName { get; set; }
        public Nullable<int> FinishKey { get; set; }
        public string CreateEmployeeName { get; set; }
        public Nullable<bool> IsOver { get; set; }
        public string AppraiseContent { get; set; }
        public Nullable<int> AppraiseLevel { get; set; }
        public Nullable<int> AppraiseImage { get; set; }
        public string AppraiseUrl { get; set; }
        public Nullable<int> MissionType { get; set; }
        public Nullable<bool> IsLook { get; set; }
        public Nullable<int> CreateEmployeeID { get; set; }
        public Nullable<int> MissionState { get; set; }
        public Nullable<int> ReturnKey { get; set; }
        public int DepartmentID { get; set; }
        public string EmployeeName { get; set; }
    }
}
