//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HA.PMS.DataAssmblly
{
    using System;
    using System.Collections.Generic;
    
    public partial class FL_MissionFile
    {
        public int FileID { get; set; }
        public int DetailedID { get; set; }
        public string FileName { get; set; }
        public string FileAddress { get; set; }
        public System.DateTime CreateDate { get; set; }
        public int EmpLoyeeID { get; set; }
        public int MissionID { get; set; }
        public Nullable<bool> IsFinish { get; set; }
    
        public virtual FL_MissionDetailed FL_MissionDetailed { get; set; }
    }
}
