//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HA.PMS.DataAssmblly
{
    using System;
    using System.Collections.Generic;
    
    public partial class FL_OrderAppraise
    {
        public int AppraiseID { get; set; }
        public Nullable<int> KindID { get; set; }
        public Nullable<int> Type { get; set; }
        public Nullable<int> Point { get; set; }
        public string PointTitle { get; set; }
        public string OrderCode { get; set; }
        public Nullable<int> OrderID { get; set; }
        public string Remark { get; set; }
        public string Suggest { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<int> CreateEmpLoyee { get; set; }
        public Nullable<int> ErroState { get; set; }
        public string AppraiseTitle { get; set; }
        public Nullable<int> SupplierID { get; set; }
        public Nullable<bool> IsOver { get; set; }
    }
}
