//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HA.PMS.DataAssmblly
{
    using System;
    using System.Collections.Generic;
    
    public partial class FL_Planner
    {
        public int PlannerID { get; set; }
        public string PlannerName { get; set; }
        public Nullable<int> PlannerSex { get; set; }
        public Nullable<int> PlannerJob { get; set; }
        public string PlannerImageName { get; set; }
        public string PlannerImagePath { get; set; }
        public string PlannerSpecial { get; set; }
        public string PlannerJobDescription { get; set; }
        public string PlannerIntrodution { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<int> CreateEmployee { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public string Remark { get; set; }
        public Nullable<int> Sort { get; set; }
    }
}
