//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HA.PMS.DataAssmblly
{
    using System;
    using System.Collections.Generic;
    
    public partial class FL_ProductitemforDispactching
    {
        public int ProductKey { get; set; }
        public int DispatchingID { get; set; }
        public string Unit { get; set; }
        public string Specifications { get; set; }
        public string ServiceContent { get; set; }
        public string Requirement { get; set; }
        public string ImageUrl { get; set; }
        public Nullable<decimal> UnitPrice { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public Nullable<decimal> Subtotal { get; set; }
        public string Remark { get; set; }
        public bool IsDelete { get; set; }
        public string CategoryName { get; set; }
        public Nullable<int> ProductID { get; set; }
        public Nullable<int> CategoryID { get; set; }
        public Nullable<int> ParentCategoryID { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public Nullable<bool> IsSvae { get; set; }
        public Nullable<int> ChangeID { get; set; }
        public Nullable<int> CreateEmployee { get; set; }
    
        public virtual FL_Dispatching FL_Dispatching { get; set; }
    }
}
