//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HA.PMS.DataAssmblly
{
    using System;
    using System.Collections.Generic;
    
    public partial class FL_QuotedPriceForType
    {
        public int ID { get; set; }
        public Nullable<int> OrderID { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public Nullable<int> QuotedID { get; set; }
        public Nullable<decimal> MPrice { get; set; }
        public Nullable<decimal> PPrice { get; set; }
        public Nullable<decimal> OPrice { get; set; }
        public Nullable<decimal> Total { get; set; }
        public Nullable<int> IsFirstMake { get; set; }
        public Nullable<int> CreateEmployee { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<int> IsLock { get; set; }
        public Nullable<decimal> WPrice { get; set; }
        public Nullable<decimal> MCostPrice { get; set; }
        public Nullable<decimal> PCostPrice { get; set; }
        public Nullable<decimal> OCostprice { get; set; }
        public Nullable<decimal> CostTotal { get; set; }
    }
}
