//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HA.PMS.DataAssmblly
{
    using System;
    using System.Collections.Generic;
    
    public partial class FL_QuotedPrice
    {
        public FL_QuotedPrice()
        {
            this.FL_CategoryForQuotedPrice = new HashSet<FL_CategoryForQuotedPrice>();
            this.FL_QuotedCollectionsPlan = new HashSet<FL_QuotedCollectionsPlan>();
            this.FL_QuotedImage = new HashSet<FL_QuotedImage>();
            this.FL_QuotedPriceItems = new HashSet<FL_QuotedPriceItems>();
            this.FL_QuotedPricefileManager = new HashSet<FL_QuotedPricefileManager>();
        }
    
        public int QuotedID { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public Nullable<int> OrderID { get; set; }
        public string OrderCoder { get; set; }
        public bool IsDelete { get; set; }
        public string CategoryName { get; set; }
        public Nullable<bool> IsChecks { get; set; }
        public string ChecksContent { get; set; }
        public string ChecksTitle { get; set; }
        public Nullable<int> EmpLoyeeID { get; set; }
        public Nullable<int> CheckState { get; set; }
        public Nullable<int> ChecksEmployee { get; set; }
        public Nullable<int> Dispatching { get; set; }
        public Nullable<decimal> EarnestMoney { get; set; }
        public Nullable<decimal> AggregateAmount { get; set; }
        public Nullable<decimal> RealAmount { get; set; }
        public Nullable<decimal> FinishAmount { get; set; }
        public Nullable<decimal> CostFinishAmount { get; set; }
        public Nullable<decimal> Noneyremaining { get; set; }
        public Nullable<bool> IsFirstCreate { get; set; }
        public Nullable<int> ParentQuotedID { get; set; }
        public string Remark { get; set; }
        public Nullable<int> IsDispatching { get; set; }
        public Nullable<int> QuotedType { get; set; }
        public Nullable<int> QuotedKind { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<bool> HaveFile { get; set; }
        public string QuotedTitle { get; set; }
        public Nullable<decimal> AddedAmount { get; set; }
        public Nullable<decimal> LessenedAmount { get; set; }
        public Nullable<bool> StarDispatching { get; set; }
        public Nullable<int> FileCheck { get; set; }
        public string PakegName { get; set; }
        public string PakegTyper { get; set; }
        public Nullable<System.DateTime> NextFlowDate { get; set; }
        public Nullable<int> SaleEmployee { get; set; }
        public Nullable<bool> FlowerCheck { get; set; }
        public Nullable<bool> MoneyCheck { get; set; }
        public Nullable<bool> BuyCheck { get; set; }
        public Nullable<int> FlowerCheckEmployee { get; set; }
        public Nullable<int> MoneyCheckEmployee { get; set; }
        public Nullable<int> BuyCheckEmployee { get; set; }
        public Nullable<int> LoseCheckEmployee { get; set; }
        public string LoseNode { get; set; }
        public Nullable<bool> LoseCheck { get; set; }
        public Nullable<int> MissionManagerEmployee { get; set; }
        public Nullable<int> DesignerEmployee { get; set; }
        public Nullable<int> DesignerState { get; set; }
        public Nullable<System.DateTime> AutualFinishDate { get; set; }
        public Nullable<System.DateTime> PlanFinishDate { get; set; }
        public Nullable<int> IsReceive { get; set; }
        public Nullable<System.DateTime> WorkCreateDate { get; set; }
        public Nullable<System.DateTime> DesignCreateDate { get; set; }
        public Nullable<int> LoseContentID { get; set; }
        public string LoseContent { get; set; }
        public Nullable<int> IsShow { get; set; }
        public Nullable<int> EarlyState { get; set; }
        public Nullable<decimal> CommissionProportion { get; set; }
        public Nullable<int> FinishState { get; set; }
        public Nullable<int> Director { get; set; }
        public string Praise { get; set; }
    
        public virtual ICollection<FL_CategoryForQuotedPrice> FL_CategoryForQuotedPrice { get; set; }
        public virtual ICollection<FL_QuotedCollectionsPlan> FL_QuotedCollectionsPlan { get; set; }
        public virtual ICollection<FL_QuotedImage> FL_QuotedImage { get; set; }
        public virtual ICollection<FL_QuotedPriceItems> FL_QuotedPriceItems { get; set; }
        public virtual ICollection<FL_QuotedPricefileManager> FL_QuotedPricefileManager { get; set; }
    }
}
