//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HA.PMS.DataAssmblly
{
    using System;
    using System.Collections.Generic;
    
    public partial class FL_QuotedPriceSchedule
    {
        public int ScheID { get; set; }
        public Nullable<int> ScheCustomerID { get; set; }
        public Nullable<int> ScheOrderID { get; set; }
        public Nullable<int> ScheQuotedID { get; set; }
        public string ScheType { get; set; }
        public string ScheName { get; set; }
        public Nullable<decimal> ScheOfferPrice { get; set; }
        public Nullable<decimal> ScheCooperatePrice { get; set; }
        public Nullable<decimal> ScheDepositPrice { get; set; }
        public Nullable<System.DateTime> ScheCreateDate { get; set; }
        public string ScheReamrk { get; set; }
        public Nullable<int> ScheCreateEmployee { get; set; }
        public Nullable<int> ScheState { get; set; }
    }
}
