//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HA.PMS.DataAssmblly
{
    using System;
    using System.Collections.Generic;
    
    public partial class FL_QuotedPriceItems
    {
        public int ChangeID { get; set; }
        public int QuotedID { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<int> CreateEmpLoyee { get; set; }
        public Nullable<int> OrderID { get; set; }
        public string Unit { get; set; }
        public string ServiceContent { get; set; }
        public string Requirement { get; set; }
        public string ImageUrl { get; set; }
        public Nullable<decimal> UnitPrice { get; set; }
        public Nullable<decimal> PurchasePrice { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<decimal> Subtotal { get; set; }
        public string Remark { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public string CategoryName { get; set; }
        public string ParentCategoryName { get; set; }
        public Nullable<int> CategoryID { get; set; }
        public Nullable<int> ParentCategoryID { get; set; }
        public Nullable<int> ProductID { get; set; }
        public Nullable<bool> IsChange { get; set; }
        public string Specifications { get; set; }
        public Nullable<bool> IsSvae { get; set; }
        public Nullable<int> ParentID { get; set; }
        public Nullable<int> Batch { get; set; }
        public Nullable<int> RowType { get; set; }
        public Nullable<int> Type { get; set; }
        public Nullable<int> ItemLevel { get; set; }
        public Nullable<int> ParentQuotedID { get; set; }
        public Nullable<decimal> ItemSaleAmount { get; set; }
        public Nullable<decimal> ItemAmount { get; set; }
        public Nullable<int> Productproperty { get; set; }
        public Nullable<bool> IsAdd { get; set; }
        public Nullable<bool> ExistAdd { get; set; }
        public Nullable<System.DateTime> PartyDay { get; set; }
        public string TimerSpan { get; set; }
        public string SupplierName { get; set; }
        public string Classification { get; set; }
        public Nullable<int> IsFirstMake { get; set; }
        public Nullable<int> IsFinishMake { get; set; }
        public Nullable<System.DateTime> ChangeDate { get; set; }
        public Nullable<int> ChangeEmployee { get; set; }
        public Nullable<decimal> Cost { get; set; }
        public Nullable<decimal> CostSubTotal { get; set; }
        public Nullable<decimal> CostItemAmount { get; set; }
        public Nullable<decimal> ItemCost { get; set; }
    
        public virtual FL_QuotedPrice FL_QuotedPrice { get; set; }
    }
}
