//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HA.PMS.DataAssmblly
{
    using System;
    using System.Collections.Generic;
    
    public partial class FL_WarningMessage
    {
        public int WMID { get; set; }
        public string MessAgeTitle { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<int> EmpLoyeeID { get; set; }
        public string ResualtAddress { get; set; }
        public Nullable<int> managerEmployee { get; set; }
        public Nullable<bool> IsLook { get; set; }
        public Nullable<int> FinishKey { get; set; }
        public Nullable<int> State { get; set; }
        public Nullable<int> CustomerID { get; set; }
    }
}
