//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HA.PMS.DataAssmblly
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class PMS_WeddingEntities : DbContext
    {
        public PMS_WeddingEntities()
            : base("name=PMS_WeddingEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Sys_Channel> Sys_Channel { get; set; }
        public DbSet<Sys_ClientManager> Sys_ClientManager { get; set; }
        public DbSet<Sys_Controls> Sys_Controls { get; set; }
        public DbSet<Sys_Department> Sys_Department { get; set; }
        public DbSet<Sys_EmpLoyeeHigherups> Sys_EmpLoyeeHigherups { get; set; }
        public DbSet<Sys_EmployeeJob> Sys_EmployeeJob { get; set; }
        public DbSet<Sys_EmployeeType> Sys_EmployeeType { get; set; }
        public DbSet<Sys_FileCategory> Sys_FileCategory { get; set; }
        public DbSet<Sys_FileDetails> Sys_FileDetails { get; set; }
        public DbSet<Sys_JurisdictionforButton> Sys_JurisdictionforButton { get; set; }
        public DbSet<Sys_Workgroups> Sys_Workgroups { get; set; }
        public DbSet<Sys_TitleNode> Sys_TitleNode { get; set; }
        public DbSet<Sys_UserJurisdiction> Sys_UserJurisdiction { get; set; }
        public DbSet<Sys_WeddingPlanning> Sys_WeddingPlanning { get; set; }
        public DbSet<CA_MyGoalTarget> CA_MyGoalTarget { get; set; }
        public DbSet<CA_Notice> CA_Notice { get; set; }
        public DbSet<CA_SaleTarget> CA_SaleTarget { get; set; }
        public DbSet<CA_TargetType> CA_TargetType { get; set; }
        public DbSet<CA_TargetTypeRateValue> CA_TargetTypeRateValue { get; set; }
        public DbSet<CA_WeddingSceneEvaluationResult> CA_WeddingSceneEvaluationResult { get; set; }
        public DbSet<CS_Complain> CS_Complain { get; set; }
        public DbSet<CS_DegreeAssessResult> CS_DegreeAssessResult { get; set; }
        public DbSet<CS_DegreeOfSatisfaction> CS_DegreeOfSatisfaction { get; set; }
        public DbSet<CS_DegreeOfSatisfactionContent> CS_DegreeOfSatisfactionContent { get; set; }
        public DbSet<CS_DegreeOfSatisfactionItem> CS_DegreeOfSatisfactionItem { get; set; }
        public DbSet<CS_InvestigateState> CS_InvestigateState { get; set; }
        public DbSet<CS_Member> CS_Member { get; set; }
        public DbSet<CS_MemberServiceMethodResult> CS_MemberServiceMethodResult { get; set; }
        public DbSet<CS_MemberServiceTypeResult> CS_MemberServiceTypeResult { get; set; }
        public DbSet<CS_TakeDisk> CS_TakeDisk { get; set; }
        public DbSet<FD_AllProducts> FD_AllProducts { get; set; }
        public DbSet<FD_BanquetHallImg> FD_BanquetHallImg { get; set; }
        public DbSet<FD_CaseFile> FD_CaseFile { get; set; }
        public DbSet<FD_Category> FD_Category { get; set; }
        public DbSet<FD_CelebrationKnowledge> FD_CelebrationKnowledge { get; set; }
        public DbSet<FD_CelebrationPackage> FD_CelebrationPackage { get; set; }
        public DbSet<FD_CelebrationPackageImage> FD_CelebrationPackageImage { get; set; }
        public DbSet<FD_CelebrationPackageMakeQuotedPrice> FD_CelebrationPackageMakeQuotedPrice { get; set; }
        public DbSet<FD_CelebrationPackagePriceSpan> FD_CelebrationPackagePriceSpan { get; set; }
        public DbSet<FD_CelebrationPackageProduct> FD_CelebrationPackageProduct { get; set; }
        public DbSet<FD_CelebrationPackageStyle> FD_CelebrationPackageStyle { get; set; }
        public DbSet<FD_ChannelType> FD_ChannelType { get; set; }
        public DbSet<FD_DeliverySchedule> FD_DeliverySchedule { get; set; }
        public DbSet<FD_GuardianImage> FD_GuardianImage { get; set; }
        public DbSet<FD_GuardianMovie> FD_GuardianMovie { get; set; }
        public DbSet<FD_GuardianType> FD_GuardianType { get; set; }
        public DbSet<FD_GuradianFile> FD_GuradianFile { get; set; }
        public DbSet<FD_GuradianLeven> FD_GuradianLeven { get; set; }
        public DbSet<FD_HotelImg> FD_HotelImg { get; set; }
        public DbSet<FD_HotelLabel> FD_HotelLabel { get; set; }
        public DbSet<FD_HotelLabelLog> FD_HotelLabelLog { get; set; }
        public DbSet<FD_ImageType> FD_ImageType { get; set; }
        public DbSet<FD_ImageWarehouse> FD_ImageWarehouse { get; set; }
        public DbSet<FD_LoseContent> FD_LoseContent { get; set; }
        public DbSet<FD_PayNeedRabate> FD_PayNeedRabate { get; set; }
        public DbSet<FD_PPTWarehouse> FD_PPTWarehouse { get; set; }
        public DbSet<FD_Product> FD_Product { get; set; }
        public DbSet<FD_ProductOrderInuse> FD_ProductOrderInuse { get; set; }
        public DbSet<FD_ProductTobeDistributed> FD_ProductTobeDistributed { get; set; }
        public DbSet<FD_QuotedCatgory> FD_QuotedCatgory { get; set; }
        public DbSet<FD_Storehouse> FD_Storehouse { get; set; }
        public DbSet<FD_StorehouseScrapLog> FD_StorehouseScrapLog { get; set; }
        public DbSet<FD_StorehouseSourceProduct> FD_StorehouseSourceProduct { get; set; }
        public DbSet<FD_StorehouseSupplierProductAll> FD_StorehouseSupplierProductAll { get; set; }
        public DbSet<FD_SupplierErrorLog> FD_SupplierErrorLog { get; set; }
        public DbSet<FD_SupplierType> FD_SupplierType { get; set; }
        public DbSet<FL_CategoryforDispatching> FL_CategoryforDispatching { get; set; }
        public DbSet<FL_CategoryForQuotedPrice> FL_CategoryForQuotedPrice { get; set; }
        public DbSet<FL_Celebration> FL_Celebration { get; set; }
        public DbSet<FL_Cost> FL_Cost { get; set; }
        public DbSet<FL_CostforEmpLoyee> FL_CostforEmpLoyee { get; set; }
        public DbSet<FL_DispatchingImage> FL_DispatchingImage { get; set; }
        public DbSet<FL_DispatchingState> FL_DispatchingState { get; set; }
        public DbSet<FL_DispatchingTeamEmployee> FL_DispatchingTeamEmployee { get; set; }
        public DbSet<FL_EmpLoyeeMissionSum> FL_EmpLoyeeMissionSum { get; set; }
        public DbSet<FL_FinishTargetSum> FL_FinishTargetSum { get; set; }
        public DbSet<FL_Invite> FL_Invite { get; set; }
        public DbSet<FL_MakeCollections> FL_MakeCollections { get; set; }
        public DbSet<FL_Message> FL_Message { get; set; }
        public DbSet<FL_MessageBoard> FL_MessageBoard { get; set; }
        public DbSet<FL_MissionChange> FL_MissionChange { get; set; }
        public DbSet<FL_MissionDetailed> FL_MissionDetailed { get; set; }
        public DbSet<FL_MissionFile> FL_MissionFile { get; set; }
        public DbSet<FL_MissionManager> FL_MissionManager { get; set; }
        public DbSet<FL_MissionSumup> FL_MissionSumup { get; set; }
        public DbSet<FL_MoneyRateSpan> FL_MoneyRateSpan { get; set; }
        public DbSet<FL_OrderAppraise> FL_OrderAppraise { get; set; }
        public DbSet<FL_OrderEarnestMoney> FL_OrderEarnestMoney { get; set; }
        public DbSet<FL_Orderfile> FL_Orderfile { get; set; }
        public DbSet<FL_OrderfinalCost> FL_OrderfinalCost { get; set; }
        public DbSet<FL_OrderGuardian> FL_OrderGuardian { get; set; }
        public DbSet<FL_OrderMessage> FL_OrderMessage { get; set; }
        public DbSet<FL_OrderMoneySpan> FL_OrderMoneySpan { get; set; }
        public DbSet<FL_OrderProjectfileManager> FL_OrderProjectfileManager { get; set; }
        public DbSet<FL_OrderReference> FL_OrderReference { get; set; }
        public DbSet<FL_QuotedImage> FL_QuotedImage { get; set; }
        public DbSet<FL_QuotedPricefileManager> FL_QuotedPricefileManager { get; set; }
        public DbSet<FL_SucessInvite> FL_SucessInvite { get; set; }
        public DbSet<FL_Target> FL_Target { get; set; }
        public DbSet<FL_Telemarketing> FL_Telemarketing { get; set; }
        public DbSet<FL_WarningMessage> FL_WarningMessage { get; set; }
        public DbSet<FL_WeddingPlanFile> FL_WeddingPlanFile { get; set; }
        public DbSet<FL_WeddingPlanning> FL_WeddingPlanning { get; set; }
        public DbSet<CS_ComplainCustomersOrderEmployee> CS_ComplainCustomersOrderEmployee { get; set; }
        public DbSet<FD_GuardianTypeLeven> FD_GuardianTypeLeven { get; set; }
        public DbSet<FD_PayNeedSales> FD_PayNeedSales { get; set; }
        public DbSet<FD_PPTWarehouseFDImageType> FD_PPTWarehouseFDImageType { get; set; }
        public DbSet<FD_ProductCategorySupplier> FD_ProductCategorySupplier { get; set; }
        public DbSet<FD_SupplierProductCount> FD_SupplierProductCount { get; set; }
        public DbSet<FL_DispatchAllProducts> FL_DispatchAllProducts { get; set; }
        public DbSet<View_CSDispatching> View_CSDispatching { get; set; }
        public DbSet<View_DepartmentTarget> View_DepartmentTarget { get; set; }
        public DbSet<View_DispatchingOrder> View_DispatchingOrder { get; set; }
        public DbSet<View_EmpLoyeeChannel> View_EmpLoyeeChannel { get; set; }
        public DbSet<View_EmployeeTarget> View_EmployeeTarget { get; set; }
        public DbSet<View_GetCostItem> View_GetCostItem { get; set; }
        public DbSet<View_GetMissionSum> View_GetMissionSum { get; set; }
        public DbSet<View_GetSupplierforCarrytask> View_GetSupplierforCarrytask { get; set; }
        public DbSet<View_GetSupplierProduct> View_GetSupplierProduct { get; set; }
        public DbSet<View_Hotels> View_Hotels { get; set; }
        public DbSet<View_MyGoalTargetType> View_MyGoalTargetType { get; set; }
        public DbSet<View_PackageProduct> View_PackageProduct { get; set; }
        public DbSet<View_StorehouseStatistics> View_StorehouseStatistics { get; set; }
        public DbSet<View_Dispatching> View_Dispatching { get; set; }
        public DbSet<View_DispatchingCustomers> View_DispatchingCustomers { get; set; }
        public DbSet<View_GetOtherMember> View_GetOtherMember { get; set; }
        public DbSet<FL_DispatchingEmployeeManager> FL_DispatchingEmployeeManager { get; set; }
        public DbSet<FD_SupplierDispatchCustomer> FD_SupplierDispatchCustomer { get; set; }
        public DbSet<View_GetCost> View_GetCost { get; set; }
        public DbSet<View_GetDegreeOfSatisfaction> View_GetDegreeOfSatisfaction { get; set; }
        public DbSet<View_GetInviteCompletetoEnd> View_GetInviteCompletetoEnd { get; set; }
        public DbSet<View_GetQuotedCostPlan> View_GetQuotedCostPlan { get; set; }
        public DbSet<View_GetWeddingPlanMission> View_GetWeddingPlanMission { get; set; }
        public DbSet<FD_QuotedProduct> FD_QuotedProduct { get; set; }
        public DbSet<FL_FlowerCost> FL_FlowerCost { get; set; }
        public DbSet<FL_CostforOrder> FL_CostforOrder { get; set; }
        public DbSet<CS_Credit> CS_Credit { get; set; }
        public DbSet<CS_CreditLog> CS_CreditLog { get; set; }
        public DbSet<View_GetInviteCustomers> View_GetInviteCustomers { get; set; }
        public DbSet<View_GetTelmarketingCustomers> View_GetTelmarketingCustomers { get; set; }
        public DbSet<SS_QuotedItemChange> SS_QuotedItemChange { get; set; }
        public DbSet<SS_QuotedSourceItem> SS_QuotedSourceItem { get; set; }
        public DbSet<FL_CelebrationProductItem> FL_CelebrationProductItem { get; set; }
        public DbSet<View_SSCustomer> View_SSCustomer { get; set; }
        public DbSet<FL_CustomerReturnVisit> FL_CustomerReturnVisit { get; set; }
        public DbSet<FD_InvestigateItem> FD_InvestigateItem { get; set; }
        public DbSet<View_GetCostPlan> View_GetCostPlan { get; set; }
        public DbSet<View_GetMember> View_GetMember { get; set; }
        public DbSet<FD_Material> FD_Material { get; set; }
        public DbSet<CC_PackageReserve> CC_PackageReserve { get; set; }
        public DbSet<FL_QuotedCollectionsPlan> FL_QuotedCollectionsPlan { get; set; }
        public DbSet<FL_InvtieContent> FL_InvtieContent { get; set; }
        public DbSet<ComplainCustomer> ComplainCustomer { get; set; }
        public DbSet<View_DispatchingDegreeOfSatisfaction> View_DispatchingDegreeOfSatisfaction { get; set; }
        public DbSet<View_EmployeeTakeDisk> View_EmployeeTakeDisk { get; set; }
        public DbSet<FL_OrderDetails> FL_OrderDetails { get; set; }
        public DbSet<CostSumTs> CostSumTs { get; set; }
        public DbSet<FL_DispathingSatisfaction> FL_DispathingSatisfaction { get; set; }
        public DbSet<FL_Dispatching> FL_Dispatching { get; set; }
        public DbSet<View_DispatchingEvaluation> View_DispatchingEvaluation { get; set; }
        public DbSet<FD_InviteReturnState> FD_InviteReturnState { get; set; }
        public DbSet<View_DesignerCustomer> View_DesignerCustomer { get; set; }
        public DbSet<View_GetDefrreSatisaction> View_GetDefrreSatisaction { get; set; }
        public DbSet<FL_DesignUpload> FL_DesignUpload { get; set; }
        public DbSet<SS_Report> SS_Report { get; set; }
        public DbSet<FL_Designclass> FL_Designclass { get; set; }
        public DbSet<FL_DesignThemes> FL_DesignThemes { get; set; }
        public DbSet<View_GetMinDateCollectionPlan> View_GetMinDateCollectionPlan { get; set; }
        public DbSet<FL_QuotedPriceSchedule> FL_QuotedPriceSchedule { get; set; }
        public DbSet<FD_SupplierProductQuery> FD_SupplierProductQuery { get; set; }
        public DbSet<View_CostSumEvaluation> View_CostSumEvaluation { get; set; }
        public DbSet<View_GetOrderCustomers> View_GetOrderCustomers { get; set; }
        public DbSet<sys_LoginLog> sys_LoginLog { get; set; }
        public DbSet<CA_CompanyFile> CA_CompanyFile { get; set; }
        public DbSet<CA_CompanySystem> CA_CompanySystem { get; set; }
        public DbSet<sys_EmployeeDataFile> sys_EmployeeDataFile { get; set; }
        public DbSet<FL_Evaulation> FL_Evaulation { get; set; }
        public DbSet<FL_Planner> FL_Planner { get; set; }
        public DbSet<FL_PlannerType> FL_PlannerType { get; set; }
        public DbSet<CA_Distrinct> CA_Distrinct { get; set; }
        public DbSet<FD_BanquetHall> FD_BanquetHall { get; set; }
        public DbSet<View_GetTakeDisk> View_GetTakeDisk { get; set; }
        public DbSet<CS_TakeDiskContent> CS_TakeDiskContent { get; set; }
        public DbSet<FL_QuotedContent> FL_QuotedContent { get; set; }
        public DbSet<FL_DetailsQuotedPrice> FL_DetailsQuotedPrice { get; set; }
        public DbSet<FL_EarlyDesigner> FL_EarlyDesigner { get; set; }
        public DbSet<FL_QuotedLoss> FL_QuotedLoss { get; set; }
        public DbSet<sys_HandleLog> sys_HandleLog { get; set; }
        public DbSet<sys_HandleType> sys_HandleType { get; set; }
        public DbSet<sys_LookURL> sys_LookURL { get; set; }
        public DbSet<FD_VisitState> FD_VisitState { get; set; }
        public DbSet<sys_WorkReport> sys_WorkReport { get; set; }
        public DbSet<View_CostSum> View_CostSum { get; set; }
        public DbSet<View_WorkReport> View_WorkReport { get; set; }
        public DbSet<sys_BugFile> sys_BugFile { get; set; }
        public DbSet<sys_BugSystem> sys_BugSystem { get; set; }
        public DbSet<CostSumDesign> CostSumDesign { get; set; }
        public DbSet<FL_ProductforDispatching> FL_ProductforDispatching { get; set; }
        public DbSet<View_CustomerQuotedSchedule> View_CustomerQuotedSchedule { get; set; }
        public DbSet<FD_Supplier> FD_Supplier { get; set; }
        public DbSet<FD_FourGuardian> FD_FourGuardian { get; set; }
        public DbSet<FL_StatementPayFor> FL_StatementPayFor { get; set; }
        public DbSet<View_CustomerEvaulation> View_CustomerEvaulation { get; set; }
        public DbSet<FD_TheCase> FD_TheCase { get; set; }
        public DbSet<FD_Hotel> FD_Hotel { get; set; }
        public DbSet<FD_SaleSources> FD_SaleSources { get; set; }
        public DbSet<FL_CostSum> FL_CostSum { get; set; }
        public DbSet<Sys_Employee> Sys_Employee { get; set; }
        public DbSet<FL_Order> FL_Order { get; set; }
        public DbSet<FL_Customers> FL_Customers { get; set; }
        public DbSet<View_CustomerQuoted> View_CustomerQuoted { get; set; }
        public DbSet<FL_QuotedPriceItems> FL_QuotedPriceItems { get; set; }
        public DbSet<FL_QuotedPrice> FL_QuotedPrice { get; set; }
        public DbSet<Sys_Config> Sys_Config { get; set; }
        public DbSet<FL_Statement> FL_Statement { get; set; }
        public DbSet<FL_QuotedPriceForType> FL_QuotedPriceForType { get; set; }
        public DbSet<view_CustomerStatement> view_CustomerStatement { get; set; }
        public DbSet<FD_ApplyType> FD_ApplyType { get; set; }
    
        public virtual ObjectResult<View_DepartmentTarget> GetDepartmentTargetinDepartmentKey(string departmentID, string getWhere)
        {
            var departmentIDParameter = departmentID != null ?
                new ObjectParameter("DepartmentID", departmentID) :
                new ObjectParameter("DepartmentID", typeof(string));
    
            var getWhereParameter = getWhere != null ?
                new ObjectParameter("GetWhere", getWhere) :
                new ObjectParameter("GetWhere", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<View_DepartmentTarget>("GetDepartmentTargetinDepartmentKey", departmentIDParameter, getWhereParameter);
        }
    
        public virtual ObjectResult<View_DepartmentTarget> GetDepartmentTargetinDepartmentKey(string departmentID, string getWhere, MergeOption mergeOption)
        {
            var departmentIDParameter = departmentID != null ?
                new ObjectParameter("DepartmentID", departmentID) :
                new ObjectParameter("DepartmentID", typeof(string));
    
            var getWhereParameter = getWhere != null ?
                new ObjectParameter("GetWhere", getWhere) :
                new ObjectParameter("GetWhere", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<View_DepartmentTarget>("GetDepartmentTargetinDepartmentKey", mergeOption, departmentIDParameter, getWhereParameter);
        }
    
        public virtual ObjectResult<View_DepartmentTarget> GetDepartmentTarget(string departmentID, string getWhere)
        {
            var departmentIDParameter = departmentID != null ?
                new ObjectParameter("DepartmentID", departmentID) :
                new ObjectParameter("DepartmentID", typeof(string));
    
            var getWhereParameter = getWhere != null ?
                new ObjectParameter("GetWhere", getWhere) :
                new ObjectParameter("GetWhere", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<View_DepartmentTarget>("GetDepartmentTarget", departmentIDParameter, getWhereParameter);
        }
    
        public virtual ObjectResult<View_DepartmentTarget> GetDepartmentTarget(string departmentID, string getWhere, MergeOption mergeOption)
        {
            var departmentIDParameter = departmentID != null ?
                new ObjectParameter("DepartmentID", departmentID) :
                new ObjectParameter("DepartmentID", typeof(string));
    
            var getWhereParameter = getWhere != null ?
                new ObjectParameter("GetWhere", getWhere) :
                new ObjectParameter("GetWhere", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<View_DepartmentTarget>("GetDepartmentTarget", mergeOption, departmentIDParameter, getWhereParameter);
        }
    
        public virtual ObjectResult<View_EmployeeTarget> GetTargetByEmpLoyeeID(string empLoyeeID, string getWhere)
        {
            var empLoyeeIDParameter = empLoyeeID != null ?
                new ObjectParameter("EmpLoyeeID", empLoyeeID) :
                new ObjectParameter("EmpLoyeeID", typeof(string));
    
            var getWhereParameter = getWhere != null ?
                new ObjectParameter("GetWhere", getWhere) :
                new ObjectParameter("GetWhere", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<View_EmployeeTarget>("GetTargetByEmpLoyeeID", empLoyeeIDParameter, getWhereParameter);
        }
    
        public virtual ObjectResult<View_EmployeeTarget> GetTargetByEmpLoyeeID(string empLoyeeID, string getWhere, MergeOption mergeOption)
        {
            var empLoyeeIDParameter = empLoyeeID != null ?
                new ObjectParameter("EmpLoyeeID", empLoyeeID) :
                new ObjectParameter("EmpLoyeeID", typeof(string));
    
            var getWhereParameter = getWhere != null ?
                new ObjectParameter("GetWhere", getWhere) :
                new ObjectParameter("GetWhere", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<View_EmployeeTarget>("GetTargetByEmpLoyeeID", mergeOption, empLoyeeIDParameter, getWhereParameter);
        }
    
        public virtual ObjectResult<View_DepartmentTarget> GetEmployeetargetbyID(string empLoyeeID, string getWhere)
        {
            var empLoyeeIDParameter = empLoyeeID != null ?
                new ObjectParameter("EmpLoyeeID", empLoyeeID) :
                new ObjectParameter("EmpLoyeeID", typeof(string));
    
            var getWhereParameter = getWhere != null ?
                new ObjectParameter("GetWhere", getWhere) :
                new ObjectParameter("GetWhere", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<View_DepartmentTarget>("GetEmployeetargetbyID", empLoyeeIDParameter, getWhereParameter);
        }
    
        public virtual ObjectResult<View_DepartmentTarget> GetEmployeetargetbyID(string empLoyeeID, string getWhere, MergeOption mergeOption)
        {
            var empLoyeeIDParameter = empLoyeeID != null ?
                new ObjectParameter("EmpLoyeeID", empLoyeeID) :
                new ObjectParameter("EmpLoyeeID", typeof(string));
    
            var getWhereParameter = getWhere != null ?
                new ObjectParameter("GetWhere", getWhere) :
                new ObjectParameter("GetWhere", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<View_DepartmentTarget>("GetEmployeetargetbyID", mergeOption, empLoyeeIDParameter, getWhereParameter);
        }
    
        public virtual ObjectResult<GetMissionSumByWhere_Result> GetMissionSumByWhere(string getWhere)
        {
            var getWhereParameter = getWhere != null ?
                new ObjectParameter("GetWhere", getWhere) :
                new ObjectParameter("GetWhere", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetMissionSumByWhere_Result>("GetMissionSumByWhere", getWhereParameter);
        }
    
        public virtual ObjectResult<View_GetMissionSum> GetMissionSum(string getWhere)
        {
            var getWhereParameter = getWhere != null ?
                new ObjectParameter("GetWhere", getWhere) :
                new ObjectParameter("GetWhere", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<View_GetMissionSum>("GetMissionSum", getWhereParameter);
        }
    
        public virtual ObjectResult<View_GetMissionSum> GetMissionSum(string getWhere, MergeOption mergeOption)
        {
            var getWhereParameter = getWhere != null ?
                new ObjectParameter("GetWhere", getWhere) :
                new ObjectParameter("GetWhere", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<View_GetMissionSum>("GetMissionSum", mergeOption, getWhereParameter);
        }
    
        public virtual ObjectResult<FL_FinishTargetSum> GetFinishTargetByID(string getWhere)
        {
            var getWhereParameter = getWhere != null ?
                new ObjectParameter("GetWhere", getWhere) :
                new ObjectParameter("GetWhere", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<FL_FinishTargetSum>("GetFinishTargetByID", getWhereParameter);
        }
    
        public virtual ObjectResult<FL_FinishTargetSum> GetFinishTargetByID(string getWhere, MergeOption mergeOption)
        {
            var getWhereParameter = getWhere != null ?
                new ObjectParameter("GetWhere", getWhere) :
                new ObjectParameter("GetWhere", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<FL_FinishTargetSum>("GetFinishTargetByID", mergeOption, getWhereParameter);
        }
    
        public virtual ObjectResult<CostSumTs> GetCostSum(Nullable<int> dispatchingID)
        {
            var dispatchingIDParameter = dispatchingID.HasValue ?
                new ObjectParameter("DispatchingID", dispatchingID) :
                new ObjectParameter("DispatchingID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CostSumTs>("GetCostSum", dispatchingIDParameter);
        }
    
        public virtual ObjectResult<CostSumTs> GetCostSum(Nullable<int> dispatchingID, MergeOption mergeOption)
        {
            var dispatchingIDParameter = dispatchingID.HasValue ?
                new ObjectParameter("DispatchingID", dispatchingID) :
                new ObjectParameter("DispatchingID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CostSumTs>("GetCostSum", mergeOption, dispatchingIDParameter);
        }
    
        public virtual ObjectResult<GetStatemetProc_Result> GetStatemetProc(Nullable<int> rowType, string getWhere)
        {
            var rowTypeParameter = rowType.HasValue ?
                new ObjectParameter("RowType", rowType) :
                new ObjectParameter("RowType", typeof(int));
    
            var getWhereParameter = getWhere != null ?
                new ObjectParameter("GetWhere", getWhere) :
                new ObjectParameter("GetWhere", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetStatemetProc_Result>("GetStatemetProc", rowTypeParameter, getWhereParameter);
        }
    
        public virtual ObjectResult<GetMissionDetailsCount_Result> GetMissionDetailsCount(Nullable<int> employeeID, Nullable<int> missionState, string getWhere, Nullable<int> type)
        {
            var employeeIDParameter = employeeID.HasValue ?
                new ObjectParameter("EmployeeID", employeeID) :
                new ObjectParameter("EmployeeID", typeof(int));
    
            var missionStateParameter = missionState.HasValue ?
                new ObjectParameter("MissionState", missionState) :
                new ObjectParameter("MissionState", typeof(int));
    
            var getWhereParameter = getWhere != null ?
                new ObjectParameter("GetWhere", getWhere) :
                new ObjectParameter("GetWhere", typeof(string));
    
            var typeParameter = type.HasValue ?
                new ObjectParameter("Type", type) :
                new ObjectParameter("Type", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetMissionDetailsCount_Result>("GetMissionDetailsCount", employeeIDParameter, missionStateParameter, getWhereParameter, typeParameter);
        }
    
        public virtual ObjectResult<GetTakeDisks_Result> GetTakeDisks(Nullable<int> customerID, Nullable<int> typeID)
        {
            var customerIDParameter = customerID.HasValue ?
                new ObjectParameter("CustomerID", customerID) :
                new ObjectParameter("CustomerID", typeof(int));
    
            var typeIDParameter = typeID.HasValue ?
                new ObjectParameter("TypeID", typeID) :
                new ObjectParameter("TypeID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetTakeDisks_Result>("GetTakeDisks", customerIDParameter, typeIDParameter);
        }
    
        public virtual ObjectResult<GetDepartmentTarget1_Result> GetDepartmentTarget1()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetDepartmentTarget1_Result>("GetDepartmentTarget1");
        }
    
        public virtual ObjectResult<GetDesignCostProc_Result> GetDesignCostProc(Nullable<int> customerID, string getWhere)
        {
            var customerIDParameter = customerID.HasValue ?
                new ObjectParameter("CustomerID", customerID) :
                new ObjectParameter("CustomerID", typeof(int));
    
            var getWhereParameter = getWhere != null ?
                new ObjectParameter("GetWhere", getWhere) :
                new ObjectParameter("GetWhere", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetDesignCostProc_Result>("GetDesignCostProc", customerIDParameter, getWhereParameter);
        }
    
        public virtual ObjectResult<GetSuppliersById_Result> GetSuppliersById(Nullable<int> supplierID, Nullable<int> rowType, string getWhere)
        {
            var supplierIDParameter = supplierID.HasValue ?
                new ObjectParameter("SupplierID", supplierID) :
                new ObjectParameter("SupplierID", typeof(int));
    
            var rowTypeParameter = rowType.HasValue ?
                new ObjectParameter("RowType", rowType) :
                new ObjectParameter("RowType", typeof(int));
    
            var getWhereParameter = getWhere != null ?
                new ObjectParameter("GetWhere", getWhere) :
                new ObjectParameter("GetWhere", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetSuppliersById_Result>("GetSuppliersById", supplierIDParameter, rowTypeParameter, getWhereParameter);
        }
    }
}
