//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HA.PMS.DataAssmblly
{
    using System;
    using System.Collections.Generic;
    
    public partial class SS_QuotedSourceItem
    {
        public int ChangeItemID { get; set; }
        public int ChangeID { get; set; }
        public string ItemTitle { get; set; }
        public string ItemNode { get; set; }
        public System.DateTime CreateDate { get; set; }
        public Nullable<decimal> Money { get; set; }
        public Nullable<int> Count { get; set; }
        public string Unite { get; set; }
        public Nullable<decimal> SalePrice { get; set; }
    }
}
