//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HA.PMS.DataAssmblly
{
    using System;
    using System.Collections.Generic;
    
    public partial class SS_Report
    {
        public int SSID { get; set; }
        public int CustomerID { get; set; }
        public Nullable<int> ContactType { get; set; }
        public string ContactMan { get; set; }
        public string ContactPhone { get; set; }
        public Nullable<System.DateTime> OrderCreateDate { get; set; }
        public Nullable<System.DateTime> OrderSucessDate { get; set; }
        public Nullable<System.DateTime> OrderLoseDate { get; set; }
        public Nullable<System.DateTime> InviteCreateDate { get; set; }
        public Nullable<System.DateTime> InviteSucessDate { get; set; }
        public Nullable<System.DateTime> InviteLoseDate { get; set; }
        public Nullable<System.DateTime> QuotedCreateDate { get; set; }
        public Nullable<System.DateTime> QuotedFileDate { get; set; }
        public Nullable<System.DateTime> QuotedDateSucessDate { get; set; }
        public Nullable<System.DateTime> WorkCreateDate { get; set; }
        public Nullable<System.DateTime> Partydate { get; set; }
        public Nullable<decimal> Emoney { get; set; }
        public Nullable<decimal> QuotedMoney { get; set; }
        public Nullable<decimal> HasReceivables { get; set; }
        public Nullable<decimal> Outstanding { get; set; }
        public Nullable<decimal> FirstMoney { get; set; }
        public Nullable<int> InviteEmployee { get; set; }
        public Nullable<int> OrderEmployee { get; set; }
        public Nullable<int> CreateEmployee { get; set; }
        public Nullable<int> QuotedEmployee { get; set; }
        public Nullable<int> WorkEmployee { get; set; }
        public System.DateTime CreateDate { get; set; }
        public Nullable<int> State { get; set; }
        public string Channel { get; set; }
        public Nullable<int> ChannelType { get; set; }
        public Nullable<bool> ISeffective { get; set; }
        public Nullable<int> OrderType { get; set; }
        public string CustomerKeyID { get; set; }
        public string CardID { get; set; }
        public Nullable<System.DateTime> GetCardDate { get; set; }
        public Nullable<int> TargetState { get; set; }
        public Nullable<int> DutyEmployee { get; set; }
        public string MoneyPerson { get; set; }
        public Nullable<decimal> PayMoney { get; set; }
        public Nullable<System.DateTime> PayDate { get; set; }
        public Nullable<bool> IsFinish { get; set; }
    }
}
