//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HA.PMS.DataAssmblly
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sys_EmployeeJob
    {
        public Sys_EmployeeJob()
        {
            this.Sys_Employee = new HashSet<Sys_Employee>();
        }
    
        public int JobID { get; set; }
        public string Jobname { get; set; }
        public Nullable<System.DateTime> createTime { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public Nullable<int> EmployeeId { get; set; }
    
        public virtual ICollection<Sys_Employee> Sys_Employee { get; set; }
    }
}
