//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HA.PMS.DataAssmblly
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sys_Controls
    {
        public Sys_Controls()
        {
            this.Sys_JurisdictionforButton = new HashSet<Sys_JurisdictionforButton>();
        }
    
        public int ControlID { get; set; }
        public string ControlName { get; set; }
        public string ConrolKey { get; set; }
        public Nullable<int> BelongByControl { get; set; }
        public string CssClass { get; set; }
        public Nullable<int> ControlType { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public Nullable<int> ChannelID { get; set; }
        public string ServerType { get; set; }
    
        public virtual ICollection<Sys_JurisdictionforButton> Sys_JurisdictionforButton { get; set; }
    }
}
