//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HA.PMS.DataAssmblly
{
    using System;
    using System.Collections.Generic;
    
    public partial class sys_BugSystem
    {
        public int BugID { get; set; }
        public string BugTitle { get; set; }
        public string BugContent { get; set; }
        public Nullable<int> CreateEmployee { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<int> State { get; set; }
        public Nullable<System.DateTime> SolDate { get; set; }
        public Nullable<int> SolEmployee { get; set; }
        public string SolRemark { get; set; }
        public Nullable<bool> IsDelete { get; set; }
    }
}
