//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HA.PMS.DataAssmblly
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_CostSumEvaluation
    {
        public int CostSumId { get; set; }
        public string Name { get; set; }
        public string Content { get; set; }
        public Nullable<decimal> Sumtotal { get; set; }
        public string CategoryName { get; set; }
        public Nullable<int> RowType { get; set; }
        public Nullable<int> Evaluation { get; set; }
        public Nullable<int> DispatchingID { get; set; }
        public string Advance { get; set; }
        public string ShortCome { get; set; }
        public Nullable<int> State { get; set; }
        public Nullable<decimal> ActualSumTotal { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public System.DateTime CreateDate { get; set; }
        public Nullable<int> OrderID { get; set; }
        public Nullable<int> QuotedID { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public string EvaluationName { get; set; }
        public Nullable<int> CreateEmployee { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public string Remark { get; set; }
        public Nullable<decimal> PayMent { get; set; }
        public Nullable<decimal> NoPayMent { get; set; }
    }
}
