//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HA.PMS.DataAssmblly
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_GetDegreeOfSatisfaction
    {
        public string Title { get; set; }
        public string AssessName { get; set; }
        public string StationContent { get; set; }
        public int ItemKey { get; set; }
        public int TypeKey { get; set; }
        public int AssessId { get; set; }
        public string SumDof { get; set; }
        public string DofContent { get; set; }
        public Nullable<System.DateTime> DofDate { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public string DegreeResult { get; set; }
        public Nullable<int> State { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
        public Nullable<int> UpdateEmployeeID { get; set; }
        public Nullable<System.DateTime> PlanDate { get; set; }
        public string Groom { get; set; }
        public Nullable<System.DateTime> GroomBirthday { get; set; }
        public string Bride { get; set; }
        public Nullable<System.DateTime> BrideBirthday { get; set; }
        public string GroomCellPhone { get; set; }
        public string BrideCellPhone { get; set; }
        public string BrideEmail { get; set; }
        public string GroomEmail { get; set; }
        public string GroomtelPhone { get; set; }
        public string BridePhone { get; set; }
        public string GroomteWeixin { get; set; }
        public string BrideWeiXin { get; set; }
        public string TimeSpans { get; set; }
        public string FirePoint { get; set; }
        public int DofKey { get; set; }
    }
}
