//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HA.PMS.DataAssmblly
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_DesignerCustomer
    {
        public Nullable<int> CustomerID { get; set; }
        public string Bride { get; set; }
        public Nullable<System.DateTime> BrideBirthday { get; set; }
        public string Groom { get; set; }
        public Nullable<System.DateTime> GroomBirthday { get; set; }
        public string BrideCellPhone { get; set; }
        public string GroomCellPhone { get; set; }
        public Nullable<int> State { get; set; }
        public Nullable<System.DateTime> RecorderDate { get; set; }
        public string Wineshop { get; set; }
        public Nullable<System.DateTime> PartyDate { get; set; }
        public Nullable<bool> FinishOver { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public int DesignclassID { get; set; }
        public string Title { get; set; }
        public string Node { get; set; }
        public int PurchaseQuantity { get; set; }
        public decimal PurchasePrice { get; set; }
        public string Unit { get; set; }
        public System.DateTime CreateDate { get; set; }
        public int CreateEmployee { get; set; }
        public decimal TotalPrice { get; set; }
        public int QuotedID { get; set; }
        public int DispatchingID { get; set; }
        public Nullable<int> DesignState { get; set; }
        public string Spec { get; set; }
        public string SupplierName { get; set; }
        public string MaterialName { get; set; }
        public Nullable<System.DateTime> QuotedDateSucessDate { get; set; }
        public int RealQuantity { get; set; }
    }
}
