//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HA.PMS.DataAssmblly
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_GetInviteCustomers
    {
        public int InviteID { get; set; }
        public Nullable<int> EmpLoyeeID { get; set; }
        public Nullable<System.DateTime> ComeDate { get; set; }
        public int CustomerID { get; set; }
        public string Groom { get; set; }
        public Nullable<System.DateTime> GroomBirthday { get; set; }
        public string Bride { get; set; }
        public Nullable<System.DateTime> BrideBirthday { get; set; }
        public string GroomCellPhone { get; set; }
        public string BrideCellPhone { get; set; }
        public string GroomEmail { get; set; }
        public string BrideEmail { get; set; }
        public string GroomtelPhone { get; set; }
        public string BridePhone { get; set; }
        public string GroomteWeixin { get; set; }
        public string BrideWeiXin { get; set; }
        public string GroomWeiBo { get; set; }
        public string BrideWeiBo { get; set; }
        public string GroomQQ { get; set; }
        public string BrideQQ { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public Nullable<bool> IsLose { get; set; }
        public Nullable<int> State { get; set; }
        public string GroomJob { get; set; }
        public string BrideJob { get; set; }
        public string CustomersType { get; set; }
        public string GroomJobCompany { get; set; }
        public string BrideJobCompany { get; set; }
        public string Operator { get; set; }
        public string OperatorRelationship { get; set; }
        public string OperatorPhone { get; set; }
        public string BanquetTypes { get; set; }
        public decimal PartyBudget { get; set; }
        public string WeddingSponsors { get; set; }
        public Nullable<System.DateTime> PartyDate { get; set; }
        public string Address { get; set; }
        public string BanquetHall { get; set; }
        public Nullable<int> TableNumber { get; set; }
        public Nullable<decimal> BanquetAt { get; set; }
        public string DinnerTime { get; set; }
        public string BanquetSales { get; set; }
        public Nullable<int> Recorder { get; set; }
        public string StoreAddress { get; set; }
        public int ChannelType { get; set; }
        public string Channel { get; set; }
        public string Referee { get; set; }
        public string GuestsStructure { get; set; }
        public string FormMarriage { get; set; }
        public string PreparationsWedding { get; set; }
        public string LikeColor { get; set; }
        public string ExpectedAtmosphere { get; set; }
        public string LikeNumber { get; set; }
        public string Hobbies { get; set; }
        public string NoTaboos { get; set; }
        public string LikeFilm { get; set; }
        public string LikeMusic { get; set; }
        public string LikePerson { get; set; }
        public string WeddingServices { get; set; }
        public string ImportantProcess { get; set; }
        public string VoidLink { get; set; }
        public string Experience { get; set; }
        public string Memorable { get; set; }
        public string TheProposal { get; set; }
        public string MemorableGift { get; set; }
        public string Aspirations { get; set; }
        public string WatchingExperience { get; set; }
        public string ParentsWish { get; set; }
        public string DesiredAppearance { get; set; }
        public string Other { get; set; }
        public string ConvenientIinvitationTime { get; set; }
        public string CustomerStatus { get; set; }
        public string Reasons { get; set; }
        public string EmployeeSelfAnalysis { get; set; }
        public string AnalysisManager { get; set; }
        public string DocumentaryRecord { get; set; }
        public string InterviewTime { get; set; }
        public Nullable<System.DateTime> Todate { get; set; }
        public string Wineshop { get; set; }
        public Nullable<System.DateTime> RecorderDate { get; set; }
        public string ReasonsExplain { get; set; }
        public Nullable<System.DateTime> ReasonsDate { get; set; }
        public string TimeSpans { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<int> CreateEmployee { get; set; }
        public string CreateEmployeeName { get; set; }
        public Nullable<int> FllowCount { get; set; }
        public Nullable<System.DateTime> AgainDate { get; set; }
        public Nullable<System.DateTime> LastFollowDate { get; set; }
        public Nullable<int> ToDepartMent { get; set; }
        public Nullable<int> ToEmpLoyee { get; set; }
        public Nullable<int> ContentID { get; set; }
        public string Title { get; set; }
        public Nullable<int> OrderEmpLoyeeID { get; set; }
        public string OperatorEmail { get; set; }
        public string OperatorWeiXin { get; set; }
        public string OperatorWeiBo { get; set; }
        public Nullable<int> ContactType { get; set; }
        public string ContactMan { get; set; }
        public string ContactPhone { get; set; }
        public Nullable<System.DateTime> OrderCreateDate { get; set; }
        public Nullable<System.DateTime> OrderSucessDate { get; set; }
        public Nullable<System.DateTime> InviteCreateDate { get; set; }
        public Nullable<System.DateTime> OrderLoseDate { get; set; }
        public Nullable<System.DateTime> InviteSucessDate { get; set; }
        public Nullable<System.DateTime> InviteLoseDate { get; set; }
        public Nullable<System.DateTime> QuotedCreateDate { get; set; }
        public Nullable<System.DateTime> QuotedDateSucessDate { get; set; }
        public Nullable<System.DateTime> QuotedFileDate { get; set; }
        public Nullable<System.DateTime> WorkCreateDate { get; set; }
        public Nullable<int> InviteEmployee { get; set; }
        public Nullable<int> OrderEmployee { get; set; }
        public Nullable<int> Expr1 { get; set; }
        public Nullable<int> QuotedEmployee { get; set; }
        public Nullable<int> ApplyType { get; set; }
    }
}
