//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HA.PMS.DataAssmblly
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_GetOtherMember
    {
        public int MemberID { get; set; }
        public int CustomerID { get; set; }
        public int CreateEmployee { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string ServiceType { get; set; }
        public string ServiceContent { get; set; }
        public Nullable<int> Type { get; set; }
        public string Groom { get; set; }
        public Nullable<System.DateTime> GroomBirthday { get; set; }
        public string Bride { get; set; }
        public Nullable<System.DateTime> BrideBirthday { get; set; }
        public string GroomCellPhone { get; set; }
        public string BrideCellPhone { get; set; }
        public string GroomEmail { get; set; }
        public string BrideEmail { get; set; }
        public string GroomtelPhone { get; set; }
        public string BridePhone { get; set; }
        public string GroomteWeixin { get; set; }
        public string BrideWeiXin { get; set; }
        public string GroomWeiBo { get; set; }
        public string BrideWeiBo { get; set; }
        public string GroomQQ { get; set; }
        public string BrideQQ { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public Nullable<int> State { get; set; }
        public Nullable<System.DateTime> PartyDate { get; set; }
        public string Address { get; set; }
        public string Channel { get; set; }
        public string Wineshop { get; set; }
        public int OrderID { get; set; }
    }
}
