//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HA.PMS.DataAssmblly
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_CustomerEvaulation
    {
        public int CustomerID { get; set; }
        public string Bride { get; set; }
        public string Groom { get; set; }
        public string ContactMan { get; set; }
        public string ContactPhone { get; set; }
        public string Wineshop { get; set; }
        public Nullable<int> State { get; set; }
        public Nullable<bool> FinishOver { get; set; }
        public Nullable<System.DateTime> PartyDate { get; set; }
        public Nullable<System.DateTime> RecorderDate { get; set; }
        public Nullable<int> EvaluationId { get; set; }
        public string EvaluationName { get; set; }
        public Nullable<int> EvalState { get; set; }
        public Nullable<System.DateTime> UpdateEvaluTime { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public Nullable<int> DispatchingID { get; set; }
        public Nullable<int> OrderID { get; set; }
        public Nullable<int> QuotedID { get; set; }
        public Nullable<int> ParentQuotedID { get; set; }
        public Nullable<decimal> FinishAmount { get; set; }
        public Nullable<int> QuotedEmployee { get; set; }
        public int DofKey { get; set; }
        public Nullable<int> SacState { get; set; }
        public string DegreeResult { get; set; }
        public string DofContent { get; set; }
        public string SumDof { get; set; }
        public string Praise { get; set; }
    }
}
