//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HA.PMS.DataAssmblly
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_GetTakeDisk
    {
        public Nullable<int> Planner { get; set; }
        public string Groom { get; set; }
        public string GroomCellPhone { get; set; }
        public Nullable<System.DateTime> PartyDate { get; set; }
        public string Wineshop { get; set; }
        public int TakeID { get; set; }
        public int CustomerID { get; set; }
        public Nullable<System.DateTime> TakePlanTime { get; set; }
        public Nullable<System.DateTime> ConsigneeTime { get; set; }
        public Nullable<System.DateTime> NoticeTime { get; set; }
        public Nullable<System.DateTime> realityTime { get; set; }
        public bool IsDelete { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public int OrderID { get; set; }
        public string Bride { get; set; }
        public string BrideCellPhone { get; set; }
        public bool IsFinish { get; set; }
        public int UpdateEmployee { get; set; }
        public int QuotedEmployee { get; set; }
        public int State { get; set; }
        public Nullable<bool> IsCheck { get; set; }
        public Nullable<System.DateTime> GetFileTime { get; set; }
        public Nullable<int> CustomerState { get; set; }
        public string Remark { get; set; }
        public Nullable<int> FirstEmployee { get; set; }
        public Nullable<int> SecondEmployee { get; set; }
        public Nullable<int> ThirdEmployee { get; set; }
        public string ConsigneeContent { get; set; }
        public string GetFileContent { get; set; }
        public string ConsigneeWork { get; set; }
        public string GetFileWork { get; set; }
        public Nullable<System.DateTime> FinishTime { get; set; }
    }
}
