//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HA.PMS.DataAssmblly
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_Hotels
    {
        public int HotelID { get; set; }
        public string HotelName { get; set; }
        public bool IsDelete { get; set; }
        public string Area { get; set; }
        public Nullable<int> StarLevel { get; set; }
        public Nullable<decimal> PriceStar { get; set; }
        public Nullable<decimal> PriceEnd { get; set; }
        public Nullable<int> DeskCount { get; set; }
        public string Tel { get; set; }
        public string Details { get; set; }
        public string Address { get; set; }
        public string Address1 { get; set; }
        public string Money1 { get; set; }
        public string Money2 { get; set; }
        public string Other { get; set; }
        public string HotelImagePath { get; set; }
    }
}
