//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HA.PMS.DataAssmblly
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_CustomerQuotedSchedule
    {
        public int CustomerID { get; set; }
        public string Bride { get; set; }
        public string BrideCellPhone { get; set; }
        public string Groom { get; set; }
        public string GroomCellPhone { get; set; }
        public Nullable<System.DateTime> PartyDate { get; set; }
        public Nullable<bool> FinishOver { get; set; }
        public Nullable<int> State { get; set; }
        public string ContactMan { get; set; }
        public string ContactPhone { get; set; }
        public Nullable<int> CreateEmployee { get; set; }
        public Nullable<int> InviteEmployee { get; set; }
        public Nullable<int> OrderEmployee { get; set; }
        public Nullable<int> EmpLoyeeID { get; set; }
        public Nullable<int> QuotedEmployee { get; set; }
        public string Wineshop { get; set; }
        public string Channel { get; set; }
        public int ChannelType { get; set; }
        public Nullable<int> OrderID { get; set; }
        public int QuotedID { get; set; }
        public System.DateTime CreateDate { get; set; }
        public Nullable<int> ScheID { get; set; }
        public Nullable<int> ScheGuardianID { get; set; }
        public Nullable<decimal> ScheGuardianPrice { get; set; }
        public Nullable<int> ScheGuardianType { get; set; }
        public Nullable<decimal> SchePayMent { get; set; }
        public Nullable<int> ScheCreateEmployee { get; set; }
        public Nullable<int> ScheState { get; set; }
        public Nullable<System.DateTime> ScheCreateDate { get; set; }
        public string ScheReamrk { get; set; }
    }
}
