//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HA.PMS.DataAssmblly
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_GetCostPlan
    {
        public string ContactMan { get; set; }
        public string ContactPhone { get; set; }
        public Nullable<System.DateTime> Partydate { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> CollectionTime { get; set; }
        public Nullable<decimal> Amountmoney { get; set; }
        public Nullable<decimal> RealityCollection { get; set; }
        public Nullable<decimal> RealityAmount { get; set; }
        public Nullable<int> CreateEmpLoyee { get; set; }
        public Nullable<int> FinancialEmployee { get; set; }
        public Nullable<int> AmountEmployee { get; set; }
        public Nullable<bool> RowLock { get; set; }
        public string Node { get; set; }
        public string MoneyType { get; set; }
        public int QuotedID { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public Nullable<int> OrderID { get; set; }
        public int PlanID { get; set; }
        public Nullable<int> IsShow { get; set; }
    }
}
